import { billingStatus, documentTotals, invoiceOutstanding, lineSubtotal, paymentsForInvoice, type SeikoCommercialDocument, type SeikoPaymentRecord } from "./seiko-billing";

export type BillingCopies = "customer" | "supplier" | "both" | "separate";
const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char]!));
const money = (value: number) => `₹${value.toFixed(2)}`;

export function billingPrintHtml(document: SeikoCommercialDocument, payments: SeikoPaymentRecord[], copies: BillingCopies, receipt?: SeikoPaymentRecord) {
  const total = documentTotals(document);
  const supplier = document.supplier;
  const invoicePayments = payments.filter(item => item.invoiceId === document.id);
  const title = receipt ? "Payment Receipt" : document.kind === "invoice" ? document.taxMode === "gst" ? "Tax Invoice" : "Invoice" : document.kind === "quotation" ? "Quotation" : "Delivery Challan";
  const labels = copies === "customer" ? ["Customer / Client Copy"] : copies === "supplier" ? ["Supplier Copy"] : ["Customer / Client Copy", "Supplier Copy"];
  const details = receipt
    ? `<h2>${money(receipt.amount)} received</h2><p>Payment date: ${escape(receipt.date)} · ${escape(receipt.mode)}</p><p>Reference: ${escape(receipt.reference || "—")}</p><p>${escape(receipt.notes)}</p><p>Against invoice <b>${escape(document.number)}</b> dated ${escape(document.issueDate)}</p>`
    : `<table><thead><tr><th>#</th><th>Item / service</th><th>Qty</th><th>Unit</th><th>Rate</th>${document.taxMode === "gst" ? "<th>GST %</th>" : ""}<th>Amount</th></tr></thead><tbody>${document.lines.map((line, index) => `<tr><td>${index + 1}</td><td>${escape(line.description)}</td><td>${line.quantity}</td><td>${escape(line.unit)}</td><td>${money(line.unitRate)}</td>${document.taxMode === "gst" ? `<td>${line.taxRate}</td>` : ""}<td>${money(lineSubtotal(line))}</td></tr>`).join("")}</tbody></table>`;
  const paymentHistory = !receipt && document.kind === "invoice" && invoicePayments.length ? `<div class="history"><b>Payments received</b>${invoicePayments.map(item => `<div>${escape(item.date)} · ${escape(item.receiptNumber)} · ${escape(item.mode)} · ${money(item.amount)}</div>`).join("")}</div>` : "";
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escape(receipt?.receiptNumber || document.number)}</title><style>
    @page{size:A4 portrait;margin:10mm}*{box-sizing:border-box}body{margin:0;color:#172e41;font:12px Arial,sans-serif;background:white}.copy{padding:4mm 2mm;overflow-wrap:anywhere}.copy+.copy{border-top:1px dashed #789;padding-top:7mm;margin-top:6mm}.separate .copy+.copy{break-before:page;border:0;margin:0;padding-top:4mm}header{display:flex;justify-content:space-between;gap:16px;border-bottom:2px solid #173d58;padding-bottom:8px}h1{font-size:22px;margin:0 0 5px}h2{font-size:18px;margin:0 0 5px}p{margin:4px 0;white-space:pre-wrap}small{font-size:10px}.meta{text-align:right}.customer{margin:10px 0}table{width:100%;border-collapse:collapse;table-layout:fixed;font-size:11px}th,td{border-bottom:1px solid #d5dce2;padding:6px 4px;text-align:right;vertical-align:top}th:first-child,td:first-child{width:5%;text-align:left}th:nth-child(2),td:nth-child(2){width:35%;text-align:left}thead{display:table-header-group}tr{break-inside:avoid}.totals{margin:10px 0 0 auto;width:65%;break-inside:avoid}.totals div{display:flex;justify-content:space-between;padding:3px 0}.balance{font-size:15px;border-top:1px solid #789;font-weight:bold}.history{font-size:10px;margin-top:8px;break-inside:avoid}.signatures{display:flex;justify-content:space-between;gap:20px;margin-top:20px;break-inside:avoid}.notes{margin-top:8px}.copyLabel{text-transform:uppercase;font-weight:bold;font-size:10px;color:#456}footer{margin-top:10px;font-size:10px}@media screen{body{width:190mm;margin:0 auto;padding:8px}}@media print{.copy{box-decoration-break:clone}}
    </style></head><body class="${copies === "separate" ? "separate" : ""}">${labels.map(label => `<article class="copy"><header><div><h1>${escape(supplier?.name || "SEIKO Tailors")}</h1><p>${escape(supplier?.address)}</p><p>${escape(supplier?.phone)}</p>${supplier?.gstin ? `<p>GSTIN: ${escape(supplier.gstin)}</p>` : ""}</div><div class="meta"><div class="copyLabel">${label}</div><h2>${title}</h2><b>${escape(receipt?.receiptNumber || document.number)}</b><p>Date: ${escape(receipt?.date || document.issueDate)}</p>${!receipt && document.dueDate ? `<p>Due: ${escape(document.dueDate)}</p>` : ""}</div></header><section class="customer"><b>${escape(document.clientName)}</b><p>${escape(document.clientAddress)}</p><p>${escape(document.clientPhone)}${document.clientGstin ? ` · GSTIN: ${escape(document.clientGstin)}` : ""}</p>${document.orderNo ? `<p>Order: ${escape(document.orderNo)}</p>` : ""}</section>${details}<section class="totals">${!receipt ? `<div><span>Subtotal</span><span>${money(total.subtotal)}</span></div>${document.taxMode === "gst" ? (document.taxTreatment === "inter_state" ? `<div><span>IGST</span><span>${money(total.igst)}</span></div>` : `<div><span>CGST</span><span>${money(total.cgst)}</span></div><div><span>SGST</span><span>${money(total.sgst)}</span></div>`) : ""}` : ""}<div><b>Invoice total</b><b>${money(total.total)}</b></div>${document.kind === "invoice" ? `<div><span>Total received</span><span>${money(paymentsForInvoice(payments, document.id))}</span></div><div class="balance"><span>Current balance</span><span>${money(invoiceOutstanding(document, payments))}</span></div>` : ""}</section>${paymentHistory}<p class="notes">${escape(document.notes)}</p>${supplier?.bank ? `<p>Payment details: ${escape(supplier.bank)}</p>` : ""}<div class="signatures"><span>Customer acknowledgement</span><span>For ${escape(supplier?.name || "SEIKO Tailors")}<br><br>Authorised signatory</span></div><footer>${receipt ? "Receipt records this payment; current balance includes all recorded payments." : document.kind === "invoice" ? `Status: ${escape(billingStatus(document, payments).replace("_", " "))}. Payment updates retain the original invoice number.` : ""}</footer></article>`).join("")}</body></html>`;
}

// Measure actual rendered copies rather than clipping long item descriptions to a fixed half-page.
export function fitBillingCopies(frame: HTMLIFrameElement, copies: BillingCopies) {
  const doc = frame.contentDocument;
  if (!doc || copies !== "both") return;
  doc.body.classList.remove("separate");
  if (doc.body.scrollHeight > 277 * 96 / 25.4) doc.body.classList.add("separate");
}
