-- Establish current snapshots; older revisions cannot be reconstructed.
CREATE TABLE seiko_storage_audit (sequence INTEGER PRIMARY KEY AUTOINCREMENT, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, actor_email TEXT, at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')), before_json TEXT, after_json TEXT);
CREATE INDEX seiko_storage_audit_entity ON seiko_storage_audit(entity_type,entity_id,sequence);
INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) SELECT 'billing-document',id,'baseline',NULL,NULL,json_object('sequence',sequence,'id',id,'data',data,'total_paise',total_paise,'cancelled',cancelled,'created_by',created_by) FROM seiko_billing_documents;
CREATE TRIGGER seiko_billing_documents_history_insert AFTER INSERT ON seiko_billing_documents BEGIN INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) VALUES('billing-document',NEW.id,'insert',NEW.created_by,NULL,json_object('sequence',NEW.sequence,'id',NEW.id,'data',NEW.data,'total_paise',NEW.total_paise,'cancelled',NEW.cancelled,'created_by',NEW.created_by)); END;
CREATE TRIGGER seiko_billing_documents_history_update AFTER UPDATE ON seiko_billing_documents BEGIN INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) VALUES('billing-document',NEW.id,'update',json_extract(NEW.data,'$.amendedBy'),json_object('sequence',OLD.sequence,'id',OLD.id,'data',OLD.data,'total_paise',OLD.total_paise,'cancelled',OLD.cancelled,'created_by',OLD.created_by),json_object('sequence',NEW.sequence,'id',NEW.id,'data',NEW.data,'total_paise',NEW.total_paise,'cancelled',NEW.cancelled,'created_by',NEW.created_by)); END;
CREATE TRIGGER seiko_billing_documents_history_delete AFTER DELETE ON seiko_billing_documents BEGIN INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) VALUES('billing-document',OLD.id,'delete',NULL,json_object('sequence',OLD.sequence,'id',OLD.id,'data',OLD.data,'total_paise',OLD.total_paise,'cancelled',OLD.cancelled,'created_by',OLD.created_by),NULL); END;
INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) SELECT 'payment',id,'baseline',NULL,NULL,json_object('sequence',sequence,'id',id,'invoice_id',invoice_id,'amount_paise',amount_paise,'data',data,'created_by',created_by) FROM seiko_billing_payments;
CREATE TRIGGER seiko_billing_payments_history_insert AFTER INSERT ON seiko_billing_payments BEGIN INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) VALUES('payment',NEW.id,'insert',NEW.created_by,NULL,json_object('sequence',NEW.sequence,'id',NEW.id,'invoice_id',NEW.invoice_id,'amount_paise',NEW.amount_paise,'data',NEW.data,'created_by',NEW.created_by)); END;
CREATE TRIGGER seiko_billing_payments_history_update AFTER UPDATE ON seiko_billing_payments BEGIN INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) VALUES('payment',NEW.id,'update',NULL,json_object('sequence',OLD.sequence,'id',OLD.id,'invoice_id',OLD.invoice_id,'amount_paise',OLD.amount_paise,'data',OLD.data,'created_by',OLD.created_by),json_object('sequence',NEW.sequence,'id',NEW.id,'invoice_id',NEW.invoice_id,'amount_paise',NEW.amount_paise,'data',NEW.data,'created_by',NEW.created_by)); END;
CREATE TRIGGER seiko_billing_payments_history_delete AFTER DELETE ON seiko_billing_payments BEGIN INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) VALUES('payment',OLD.id,'delete',NULL,json_object('sequence',OLD.sequence,'id',OLD.id,'invoice_id',OLD.invoice_id,'amount_paise',OLD.amount_paise,'data',OLD.data,'created_by',OLD.created_by),NULL); END;
INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) SELECT 'client',id,'baseline',NULL,NULL,json_object('id',id,'name_key',name_key,'phone_key',phone_key,'email_key',email_key,'archived',archived,'data',data,'created_by',created_by,'updated_by',updated_by) FROM seiko_clients;
CREATE TRIGGER seiko_clients_history_insert AFTER INSERT ON seiko_clients BEGIN INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) VALUES('client',NEW.id,'insert',NEW.created_by,NULL,json_object('id',NEW.id,'name_key',NEW.name_key,'phone_key',NEW.phone_key,'email_key',NEW.email_key,'archived',NEW.archived,'data',NEW.data,'created_by',NEW.created_by,'updated_by',NEW.updated_by)); END;
CREATE TRIGGER seiko_clients_history_update AFTER UPDATE ON seiko_clients BEGIN INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) VALUES('client',NEW.id,'update',NEW.updated_by,json_object('id',OLD.id,'name_key',OLD.name_key,'phone_key',OLD.phone_key,'email_key',OLD.email_key,'archived',OLD.archived,'data',OLD.data,'created_by',OLD.created_by,'updated_by',OLD.updated_by),json_object('id',NEW.id,'name_key',NEW.name_key,'phone_key',NEW.phone_key,'email_key',NEW.email_key,'archived',NEW.archived,'data',NEW.data,'created_by',NEW.created_by,'updated_by',NEW.updated_by)); END;
CREATE TRIGGER seiko_clients_history_delete AFTER DELETE ON seiko_clients BEGIN INSERT INTO seiko_storage_audit(entity_type,entity_id,action,actor_email,before_json,after_json) VALUES('client',OLD.id,'delete',NULL,json_object('id',OLD.id,'name_key',OLD.name_key,'phone_key',OLD.phone_key,'email_key',OLD.email_key,'archived',OLD.archived,'data',OLD.data,'created_by',OLD.created_by,'updated_by',OLD.updated_by),NULL); END;
CREATE TRIGGER seiko_storage_audit_no_update BEFORE UPDATE ON seiko_storage_audit BEGIN SELECT RAISE(ABORT,'Storage audit history is immutable'); END;
CREATE TRIGGER seiko_storage_audit_no_delete BEFORE DELETE ON seiko_storage_audit BEGIN SELECT RAISE(ABORT,'Storage audit history is immutable'); END;
