"use client";
import { useEffect, useMemo, useState } from 'react';
import { ProductionSetup } from './production';
import { completedQuantity, cuttingGroups, issuedQuantity, productionDemand, type ProductionAllocation, type ProductionHandoff, type ProductionLedger, type ProductionOrder } from './lib/production-handoffs';

type Choice={orderId:string;orderNo:string;client:string;status:string;deliveryDate:string};
type Summary={id:string;number:string;name:string;status:string;purpose:string};
type Shared = {choices?:Choice[];total?:number;page?:number;handoffs?:Summary[];handoffTotal?:number;handoffPage?:number;ok:boolean;message?:string;ledger:ProductionLedger;version:number;orders:ProductionOrder[]};
const initial:Shared={ok:true,ledger:{handoffs:[]},version:0,orders:[]};
export function Production({businessId,canManage,initialOrderId,onHome}:{businessId:string;canManage:boolean;initialOrderId?:string;onHome:()=>void}) {
  const [shared,setShared]=useState(initial),[busy,setBusy]=useState(false),[ready,setReady]=useState(false);
  const [error,setError]=useState(''),[message,setMessage]=useState(''),[setup,setSetup]=useState(false);
  const [selected,setSelected]=useState<string[]>(initialOrderId?[initialOrderId]:[]),[draft,setDraft]=useState<ProductionHandoff|null>(()=>{try{return typeof window==='undefined'?null:JSON.parse(sessionStorage.getItem(`jinam:${businessId}:production-draft`)||'null');}catch{return null;}}),[openId,setOpenId]=useState('');
  const [amounts,setAmounts]=useState<Record<string,string>>({}),[search,setSearch]=useState('');
  const [status,setStatus]=useState('Open'),[page,setPage]=useState(1),[deliveryFrom,setDeliveryFrom]=useState(''),[deliveryTo,setDeliveryTo]=useState(''),[handoffPage,setHandoffPage]=useState(1),[handoffSearch,setHandoffSearch]=useState(''),[handoffStatus,setHandoffStatus]=useState('Active');
  const [selectionNames,setSelectionNames]=useState<Record<string,string>>({});
  const [quantityProduct,setQuantityProduct]=useState(''),[quantityPage,setQuantityPage]=useState(1);
  const [allocationProduct,setAllocationProduct]=useState('');
  const [sheet,setSheet]=useState('cutting'),[bundleSize,setBundleSize]=useState(20),[note,setNote]=useState('');
  const [work,setWork]=useState({allocationKey:'',operation:'Cutting',quantity:0,rejects:0,extras:0,reason:''});
  useEffect(()=>{try{if(draft)sessionStorage.setItem(`jinam:${businessId}:production-draft`,JSON.stringify(draft));else sessionStorage.removeItem(`jinam:${businessId}:production-draft`);}catch{/* Shared save remains explicit; open edits are retained in memory. */}const warn=(event:BeforeUnloadEvent)=>{if(draft){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[draft,businessId]);
  const request=async(body:Record<string,unknown>)=>{
    const response=await fetch('/api/erp/production',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({businessId,...body}),cache:'no-store',redirect:'manual'});
    if(response.status===401||response.type==='opaqueredirect')throw new Error('Sign in in another tab, then retry here. Your edits remain open.');
    let result:Shared;try{result=await response.json();}catch{throw new Error('Shared storage did not confirm this action. Your edits remain open.');}
    if(!response.ok||!result.ok)throw new Error(result.message||'Production could not be saved.');return result;
  };
  const listBody={operation:'list',orderIds:openId?[]:[...new Set([...selected,...(draft?.allocations||[]).map(row=>row.orderId)])],id:openId,search,status,page,deliveryFrom,deliveryTo,handoffPage,handoffSearch,handoffStatus};
  useEffect(()=>{let active=true;const timer=setTimeout(()=>{setBusy(true);void request(listBody).then(result=>{if(active){setShared(result);setReady(true);setError('');}}).catch(cause=>{if(active)setError(cause.message||'Production storage is unreachable.');}).finally(()=>{if(active)setBusy(false);});},250);return()=>{active=false;clearTimeout(timer);};
  // Values, rather than the request object, identify a search. Stale responses are ignored.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  },[businessId,search,status,page,deliveryFrom,deliveryTo,handoffPage,handoffSearch,handoffStatus,selected.join('|'),openId]);
  const refresh=async()=>{setBusy(true);setError('');try{setShared(await request(listBody));setReady(true);setMessage(draft?'Latest data loaded. Review open draft quantities against the updated demand.':'Production refreshed.');}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}};
  const demand=useMemo(()=>productionDemand(shared.orders),[shared.orders]);
  const open=shared.ledger.handoffs.find(item=>item.id===openId)||null;
  const active=draft||open;
  const editProduct=active?.allocations.some(row=>row.product===allocationProduct)?allocationProduct:active?.allocations[0]?.product||'';
  const editRows=active?.allocations.filter(row=>row.product===editProduct)||[];
  const filtered=demand.filter(row=>selected.includes(row.orderId));
  const remaining=(row:typeof demand[number])=>Math.max(0,row.quantity-issuedQuantity(shared.ledger,row,draft?.id));
  const quantityRows=quantityProduct==='All products'?filtered:filtered.filter(row=>row.product===quantityProduct);
  const quantityPages=Math.max(1,Math.ceil(quantityRows.length/25));
  const shownQuantityPage=Math.min(quantityPage,quantityPages);
  const changed=shared.ledger.handoffs.filter(item=>item.status!=='Draft'&&item.status!=='Cancelled'&&item.purpose==='normal').flatMap(item=>item.allocations.filter(row=>{const current=demand.find(value=>value.key===row.key);return !current||issuedQuantity(shared.ledger,current)>current.quantity;}).map(row=>({handoff:item.number,row})));
  const mutate=async(operation:string,extra:Record<string,unknown>={})=>{
    setBusy(true);setError('');setMessage('');try{
      const result=await request({operation,expectedVersion:shared.version,id:openId,orderIds:[],...extra});setShared(previous=>({...previous,...result}));setReady(true);
      if(operation==='save'){setOpenId(draft!.id);setDraft(null);setMessage('Draft saved to shared storage. Quantities are reserved only when released.');}
      else setMessage(operation==='release'?'Handoff released. Quantities are now allocated.':'Production saved to shared storage.');
      setNote('');if(operation==='event')setWork({...work,quantity:0,rejects:0,extras:0,reason:''});
    }catch(cause){setError((cause as Error).message||'Storage is unreachable. Your edits remain open.');}finally{setBusy(false);}
  };
  const create=()=>{
    const allocations:ProductionAllocation[]=[];
    for(const row of filtered){const quantity=Number(amounts[row.key]??remaining(row));if(quantity>0)allocations.push({...row,quantity,lay:'',stack:''});}
    setDraft({id:crypto.randomUUID(),number:'New draft',name:'Production handoff',status:'Draft',purpose:'normal',reason:'',allocations,lays:[],events:[],history:[],createdAt:new Date().toISOString()});setOpenId('');setError('');setMessage('');
  };
  const patchAllocation=(key:string,change:Partial<ProductionAllocation>)=>setDraft(value=>value?{...value,allocations:value.allocations.map(row=>row.key===key?{...row,...change}:row)}:value);
  const ticketCount=active?.allocations.reduce((n,row)=>n+Math.ceil(row.quantity/bundleSize),0)||0;
  const tickets=ticketCount<=2000?active?.allocations.flatMap((row,index)=>Array.from({length:Math.ceil(row.quantity/bundleSize)},(_,ticket)=>({id:`${active.number}-B${bundleSize}-${index+1}-${ticket+1}`,row,quantity:Math.min(bundleSize,row.quantity-ticket*bundleSize)})))||[]:[];
  if(setup)return <><div className="page"><button className="secondary" onClick={()=>setSetup(false)}>← Back to Production</button></div><ProductionSetup businessId={businessId} canManage={canManage}/></>;
  return <section className="page productionWorkspace">
    <button className="secondary productionNoPrint" onClick={onHome}>← Back to Home</button>
    <header className="productionWorkspaceHead"><div><p className="eyebrow">PRODUCTION</p><h1>Production handoffs</h1><p>Combine compatible work from several orders while keeping every order allocation.</p></div><div className="productionNoPrint"><button className="secondary" onClick={()=>setSetup(true)}>Planning preferences</button><button className="secondary" disabled={busy} onClick={()=>void refresh()}>Refresh</button></div></header>
    {error&&<p className="productionSaveError productionNoPrint" role="alert">{error}</p>}{message&&<p role="status" className="productionNotice productionNoPrint">{message}</p>}
    {!ready&&<p>Load shared orders and handoffs to continue.</p>}
    {changed.length>0&&<details className="panel productionNoPrint"><summary>Issued work needs review: source demand changed</summary><p>Released instructions stay fixed. Review affected work with the team before cancelling unused work or issuing a correction.</p>{changed.map((item,index)=><p key={index}>{item.handoff} · {item.row.orderNo} · {item.row.product} · {item.row.variant}: previously issued {item.row.quantity}; current demand {demand.find(row=>row.key===item.row.key)?.quantity||0}.</p>)}</details>}
    {!active&&<>
      <section className="panel productionNoPrint"><h2>Select orders</h2><div className="productionSearchFilters"><label>Find order, client or product<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Order number, client or product"/></label><label>Order status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}>{['Open','All','Draft','Active','Production','QC 1','Packing','QC 2','On Hold','Completed','Cancelled'].map(value=><option key={value}>{value}</option>)}</select></label><label>Delivery from<input type="date" value={deliveryFrom} onChange={e=>{setDeliveryFrom(e.target.value);setPage(1);}}/></label><label>Delivery to<input type="date" value={deliveryTo} onChange={e=>{setDeliveryTo(e.target.value);setPage(1);}}/></label></div>
      <div className="productionSelectionTray"><b>{selected.length} / 25 orders selected</b>{selected.map(id=><button key={id} className="secondary" onClick={()=>setSelected(all=>all.filter(value=>value!==id))} aria-label={`Remove selected ${selectionNames[id]||id}`}>{selectionNames[id]||shared.orders.find(item=>item.order.orderId===id)?.order.details.orderNo||id} ×</button>)}</div>
      <div className="productionOrderList" aria-busy={busy}>{(shared.choices||[]).map(order=><label key={order.orderId} aria-label={`${order.orderNo} · ${order.client}`}><input type="checkbox" checked={selected.includes(order.orderId)} disabled={busy||(!selected.includes(order.orderId)&&selected.length>=25)} onChange={e=>{setBusy(true);setSelectionNames(names=>({...names,[order.orderId]:`${order.orderNo} · ${order.client}`}));setSelected(all=>e.target.checked?[...all,order.orderId]:all.filter(id=>id!==order.orderId));}}/><b>{order.orderNo} · {order.client}</b><span>{order.status}</span><span>Delivery {order.deliveryDate||'not set'}</span></label>)}</div>
      {ready&&!busy&&!shared.choices?.length&&<p>No orders match these filters.</p>}<div className="productionActions"><span>{shared.total||0} matching orders · Page {page} of {Math.max(1,Math.ceil((shared.total||0)/25))}</span><button className="secondary" disabled={busy||page<=1} onClick={()=>setPage(value=>value-1)}>Previous orders</button><button className="secondary" disabled={busy||page*25>=(shared.total||0)} onClick={()=>setPage(value=>value+1)}>Next orders</button></div>
      {selected.length>0&&<><h3>Quantities for this handoff</h3><div className="productionProductTabs">{[...new Set(filtered.map(row=>row.product))].map(product=><button key={product} className={quantityProduct===product?'primary':'secondary'} onClick={()=>{setQuantityProduct(product);setQuantityPage(1);}}>{product} · {filtered.filter(row=>row.product===product).reduce((n,row)=>n+remaining(row),0)} remaining</button>)}</div><label>Product quantities<select aria-label="Product quantities" value={quantityProduct} onChange={e=>{setQuantityProduct(e.target.value);setQuantityPage(1);}}><option value="">Choose a product to review sizes</option><option>All products</option>{[...new Set(filtered.map(row=>row.product))].map(product=><option key={product}>{product}</option>)}</select></label><p>Leave zero to exclude a product or size. Unresolved details remain visible here and cannot be released. Issued quantities include closed handoffs.</p><div className="productionTableWrap productionEditorTable"><table><thead><tr><th>Order / product</th><th>Size / specifications</th><th>Demand</th><th>Issued</th><th>Include</th></tr></thead><tbody>{quantityRows.slice((shownQuantityPage-1)*25,shownQuantityPage*25).map(row=><tr key={row.key}><td><b>{row.product}</b><br/>{row.orderNo} · {row.client}</td><td>{row.variant}<br/>{row.specifications}{row.unresolved&&<strong className="productionWarning">Needs details</strong>}</td><td>{row.quantity}</td><td>{issuedQuantity(shared.ledger,row)}</td><td><input aria-label={`Include ${row.orderNo} ${row.product} ${row.variant}`} type="number" min="0" step="1" disabled={row.unresolved||!canManage} value={row.unresolved?0:amounts[row.key]??remaining(row)} onChange={e=>setAmounts(all=>({...all,[row.key]:e.target.value}))}/></td></tr>)}</tbody></table></div>{!quantityProduct&&<p>Choose a product above to review or adjust its sizes. All selected products remain included.</p>}{quantityProduct&&<div className="productionActions"><span>{quantityRows.length} size / order rows · Page {shownQuantityPage} of {quantityPages}</span><button className="secondary" disabled={shownQuantityPage<=1} onClick={()=>setQuantityPage(shownQuantityPage-1)}>Previous quantities</button><button className="secondary" disabled={shownQuantityPage>=quantityPages} onClick={()=>setQuantityPage(shownQuantityPage+1)}>Next quantities</button></div>}<button className="primary" disabled={!ready||!canManage||busy||!filtered.some(row=>!row.unresolved&&Number(amounts[row.key]??remaining(row))>0)} onClick={create}>Create handoff draft</button></>}
      </section>
      <section className="panel productionNoPrint"><h2>Saved handoffs</h2><div className="productionSearchFilters"><label>Find handoff<input value={handoffSearch} onChange={e=>{setHandoffSearch(e.target.value);setHandoffPage(1);}}/></label><label>Handoff list<select value={handoffStatus} onChange={e=>{setHandoffStatus(e.target.value);setHandoffPage(1);}}><option>Active</option><option>History</option><option>All</option></select></label></div>{!shared.handoffs?.length&&<p>{ready?'No matching handoffs. Select orders to begin.':'Saved handoffs will appear after shared storage loads.'}</p>}{(shared.handoffs||[]).map(item=><div className="productionSavedRow" key={item.id}><button className="productionTextButton" disabled={busy} onClick={()=>{setOpenId(item.id);setMessage('');setError('');}}><b>{item.number} · {item.name}</b></button><b>{item.status}</b><span>{item.purpose}</span></div>)}<div className="productionActions"><span>{shared.handoffTotal||0} handoffs · Page {handoffPage}</span><button className="secondary" disabled={busy||handoffPage<=1} onClick={()=>setHandoffPage(value=>value-1)}>Previous handoffs</button><button className="secondary" disabled={busy||handoffPage*25>=(shared.handoffTotal||0)} onClick={()=>setHandoffPage(value=>value+1)}>Next handoffs</button></div></section>
    </>}
    {active&&<>
      <section className="panel productionNoPrint"><div className="productionActions"><button className="secondary" disabled={busy} onClick={()=>{if(draft&&!window.confirm('Discard these unsaved handoff edits?'))return;setDraft(null);setOpenId('');}}>← Handoffs</button><strong>{active.number} · {active.status}{draft?' · Unsaved changes':''}</strong></div>
      {draft?<><label>Handoff name<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Purpose<select value={draft.purpose} onChange={e=>setDraft({...draft,purpose:e.target.value as ProductionHandoff['purpose']})}><option value="normal">Order demand</option><option value="rework">Authorised rework</option><option value="extra">Authorised extra production</option></select></label><label>Reason / instructions<textarea value={draft.reason} onChange={e=>setDraft({...draft,reason:e.target.value})}/></label><button className="primary" disabled={busy} onClick={()=>void mutate('save',{handoff:draft})}>Save handoff draft</button></>:<><h2>{active.name}</h2><p>{active.purpose} {active.reason&&`· ${active.reason}`}</p>{canManage&&<div className="productionActions">{active.status==='Draft'&&<><button className="secondary" disabled={busy} onClick={()=>setDraft(structuredClone(active))}>Edit draft</button><button className="primary" disabled={busy} onClick={()=>void mutate('release')}>Release handoff</button></>}{!['Closed','Cancelled'].includes(active.status)&&<><label>Closure / cancellation note<input value={note} onChange={e=>setNote(e.target.value)}/></label>{['Released','In progress'].includes(active.status)&&<button className="secondary" disabled={busy||!note.trim()} onClick={()=>void mutate('close',{reason:note})}>Close handoff</button>}{!active.events.length&&<button className="secondary" disabled={busy||!note.trim()} onClick={()=>void mutate('cancel',{reason:note})}>Cancel unused handoff</button>}</>}</div>}</>}
      </section>
      {draft&&<section className="panel productionNoPrint"><h2>Allocations</h2><div className="productionProductTabs" role="group" aria-label="Products to edit">{[...new Set(draft.allocations.map(row=>row.product))].map(product=><button key={product} className={editProduct===product?'primary':'secondary'} aria-pressed={editProduct===product} onClick={()=>setAllocationProduct(product)}>{product} · {draft.allocations.filter(row=>row.product===product).reduce((n,row)=>n+row.quantity,0)} pieces</button>)}</div><p>{editRows.length} size / order allocations for {editProduct}. Other products stay included in this handoff.</p><p>Save, then release to reserve these quantities. Refresh checks the latest orders without discarding edits. To accept a source revision, review and use Update source details.</p><div className="productionTableWrap productionEditorTable"><table><thead><tr><th>Order / product / variant</th><th>Quantity</th><th>Lay</th><th>Fabric / colour stack</th><th>Review</th></tr></thead><tbody>{editRows.map(row=>{const current=demand.find(item=>item.key===row.key);return <tr key={row.key}><td><b>{row.orderNo} · {row.product}</b><br/>{row.variant}<br/>{row.specifications}{(!current||current.sourceVersion!==row.sourceVersion)&&<strong className="productionWarning">Source changed</strong>}</td><td><input aria-label={`Handoff quantity ${row.orderNo} ${row.product} ${row.variant}`} type="number" min="1" step="1" value={row.quantity} onChange={e=>patchAllocation(row.key,{quantity:Number(e.target.value)})}/></td><td><select aria-label={`Lay ${row.orderNo} ${row.product} ${row.variant}`} value={row.lay} onChange={e=>patchAllocation(row.key,{lay:e.target.value})}><option value="">No lay planning</option>{draft.lays.map(lay=><option value={lay.id} key={lay.id}>{lay.id}</option>)}</select></td><td><input aria-label={`Stack ${row.orderNo} ${row.product} ${row.variant}`} value={row.stack} onChange={e=>patchAllocation(row.key,{stack:e.target.value})}/></td><td>{current&&<button className="secondary" onClick={()=>patchAllocation(row.key,{...current,quantity:row.quantity})}>Update source details</button>}<button className="secondary" onClick={()=>setDraft({...draft,allocations:draft.allocations.filter(item=>item.key!==row.key)})}>Remove allocation</button></td></tr>;})}</tbody></table></div>
      <details><summary>Optional cutting lays and fabric stacks</summary><p>Matching product names and sizes suggest combined demand only. The cutting master must confirm pattern, fabric width, stretch, grain, print direction and checks before sharing a lay. Different colours can use separate stacks.</p>{draft.lays.map((lay,index)=><fieldset key={lay.id}><legend>{lay.id}</legend><div className="productionLayFields">{(['pattern','fabric','width','stretch','grain','direction','checks'] as const).map(key=><label key={key} aria-label={key}>{({pattern:'Cutting pattern / shape',fabric:'Fabric type',width:'Usable fabric width',stretch:'Stretch',grain:'Grain direction',direction:'Print / nap direction',checks:'Checks / stripe matching'})[key]}<input aria-label={`${lay.id} ${key}`} value={lay[key]} onChange={e=>setDraft({...draft,lays:draft.lays.map((item,i)=>i===index?{...item,[key]:e.target.value,confirmed:false}:item)})}/></label>)}</div><label><input type="checkbox" checked={lay.confirmed} onChange={e=>setDraft({...draft,lays:draft.lays.map((item,i)=>i===index?{...item,confirmed:e.target.checked}:item)})}/>Cutting master confirmed compatibility for all assigned stacks</label></fieldset>)}<button className="secondary" onClick={()=>setDraft({...draft,lays:[...draft.lays,{id:`Lay ${draft.lays.length+1}`,pattern:'',fabric:'',width:'',stretch:'',grain:'',direction:'',checks:'',confirmed:false}]})}>Add cutting lay</button></details></section>}
      {!draft&&active.status!=='Cancelled'&&active.allocations.some(row=>demand.find(item=>item.key===row.key)?.sourceVersion!==row.sourceVersion)&&<section className="panel productionNoPrint"><h2>Source order changes since this handoff</h2><p>Issued instructions above stay fixed. Positive differences are additions to source demand; negative differences need team review. New variants appear in the order selection list. Use a new handoff for remaining demand, or explicitly authorised rework / extra production.</p>{active.allocations.filter(row=>demand.find(item=>item.key===row.key)?.sourceVersion!==row.sourceVersion).map(row=>{const current=demand.find(item=>item.key===row.key);const difference=(current?.quantity||0)-row.sourceQuantity;return <p key={row.key}>{row.orderNo} · {row.product} · {row.variant}: source demand at issue {row.sourceQuantity}, now {current?.quantity||0}; difference {difference>0?'+':''}{difference}. This handoff issued {row.quantity}.</p>;})}</section>}
      <section className="panel productionNoPrint"><h2>Team sheets</h2><div className="productionActions"><label>Sheet<select aria-label="Sheet" value={sheet} onChange={e=>setSheet(e.target.value)}><option value="cutting">Cutting quantities</option><option value="stitching">Stitching specifications</option><option value="allocation">Order allocation</option><option value="bundles">Bundle tickets</option></select></label>{sheet==='bundles'&&<label>Pieces per bundle<input type="number" min="1" max="500" value={bundleSize} onChange={e=>setBundleSize(Math.min(500,Math.max(1,Number(e.target.value)||1)))}/></label>}<button className="primary" onClick={()=>window.print()}>Print / Save PDF</button></div><p>Use your browser’s Save as PDF destination to download. {active.status==='Draft'?'Draft sheets are marked NOT RELEASED.':'Released sheets preserve the issued quantities and order details.'}</p></section>
      <section className="productionPrintSheet productionSheetPreview"><h2>{active.number} · {active.name}</h2><p><b>{active.status==='Draft'?'DRAFT — NOT RELEASED':active.status.toUpperCase()}</b> · {sheet==='cutting'?'Cutting quantities':sheet==='stitching'?'Stitching specifications':sheet==='allocation'?'Order allocation':'Bundle tickets'} · {active.allocations.reduce((n,row)=>n+row.quantity,0)} pieces</p>{active.reason&&<p>{active.reason}</p>}
      {sheet==='cutting'&&<>{[...new Set(active.allocations.map(row=>row.product))].map(product=><section className="productionProductTable" key={product}><h3>{product}</h3><table><thead><tr><th>Size / measurements</th><th>Quantity</th><th>Fabric / stack split</th></tr></thead><tbody>{cuttingGroups(active.allocations.filter(row=>row.product===product)).map((group,index)=><tr key={index}><td>{group.variant}</td><td><b>{group.quantity}</b><details className="productionNoPrint"><summary>Trace quantity</summary>{group.allocations.map(row=><p key={row.key}>{row.orderNo} · {row.client}: {row.quantity}</p>)}</details></td><td>{[...new Set(group.allocations.map(row=>`${row.specifications}${row.lay?` · ${row.lay} · ${row.stack}`:''}`))].map(spec=><div key={spec}>{spec||'—'}: <b>{group.allocations.filter(row=>`${row.specifications}${row.lay?` · ${row.lay} · ${row.stack}`:''}`===spec).reduce((n,row)=>n+row.quantity,0)}</b></div>)}</td></tr>)}</tbody><tfoot><tr><th>Total {product}</th><td colSpan={2}>{active.allocations.filter(row=>row.product===product).reduce((n,row)=>n+row.quantity,0)}</td></tr></tfoot></table></section>)}{active.lays.map(lay=><div className="productionLaySummary" key={lay.id}><h3>{lay.id} · {lay.pattern}</h3><p>{lay.fabric} · Width {lay.width} · Stretch {lay.stretch} · Grain {lay.grain} · Direction {lay.direction} · Checks {lay.checks} · {lay.confirmed?'Compatibility confirmed':'Not confirmed'}</p>{active.allocations.filter(row=>row.lay===lay.id).map(row=><p key={row.key}>{row.stack}: {row.orderNo} · {row.product} · {row.variant} · {row.quantity} pieces</p>)}</div>)}</>}
      {(sheet==='stitching'||sheet==='allocation')&&<div className="productionTableWrap productionEditorTable"><table><thead><tr><th>Order / client</th><th>Product / size</th><th>Specifications / stack</th><th>Quantity</th></tr></thead><tbody>{active.allocations.map(row=><tr key={row.key}><td>{row.orderNo}<br/>{row.client}</td><td>{row.product}<br/>{row.variant}</td><td>{row.specifications}<br/>{row.lay} {row.stack}</td><td>{row.quantity}</td></tr>)}</tbody></table></div>}
      {sheet==='bundles'&&ticketCount>2000&&<p>Increase pieces per bundle to keep this print run within 2,000 tickets.</p>}{sheet==='bundles'&&<div className="productionTickets">{tickets.map(ticket=><article key={ticket.id}><b>{ticket.id}</b><p>{ticket.row.orderNo} · {ticket.row.client}</p><strong>{ticket.row.product} · {ticket.quantity} pieces</strong><p>{ticket.row.variant}</p><p>{ticket.row.specifications}</p><p>{ticket.row.lay} · {ticket.row.stack}</p></article>)}</div>}
      </section>
      {!draft&&<section className="panel productionNoPrint"><h2>Recorded work</h2><p>Totals are per operation. Rejects and authorised extras are separate from good pieces and never increase customer order quantities. Closing a handoff does not mark an order complete.</p><div className="productionTableWrap productionEditorTable"><table><thead><tr><th>Allocation</th><th>Operation</th><th>Good / remaining</th><th>Rejects / extras</th></tr></thead><tbody>{active.allocations.map(row=><tr key={row.key}><td>{row.orderNo} · {row.product}<br/>{row.variant}</td><td>{work.operation}</td><td>{completedQuantity(active,row.key,work.operation)} / {Math.max(0,row.quantity-completedQuantity(active,row.key,work.operation))}</td><td>{active.events.filter(event=>event.allocationKey===row.key&&event.operation.trim().toLocaleLowerCase()===work.operation.trim().toLocaleLowerCase()).reduce((n,event)=>n+event.rejects,0)} / {active.events.filter(event=>event.allocationKey===row.key&&event.operation.trim().toLocaleLowerCase()===work.operation.trim().toLocaleLowerCase()).reduce((n,event)=>n+event.extras,0)}</td></tr>)}</tbody></table></div>
      {canManage&&['Released','In progress'].includes(active.status)&&<form onSubmit={e=>{e.preventDefault();void mutate('event',{event:work});}}><div className="productionLayFields"><label>Work allocation<select aria-label="Work allocation" required value={work.allocationKey} onChange={e=>setWork({...work,allocationKey:e.target.value})}><option value="">Select allocation</option>{active.allocations.map(row=><option key={row.key} value={row.key}>{row.orderNo} · {row.product} · {row.variant}</option>)}</select></label><label>Operation<input required list="productionOperations" value={work.operation} onChange={e=>setWork({...work,operation:e.target.value})}/><datalist id="productionOperations"><option>Cutting</option><option>Stitching</option><option>Finishing</option><option>Inspection</option></datalist></label>{(['quantity','rejects','extras'] as const).map(key=><label key={key}>{key==='quantity'?'Good pieces':key==='rejects'?'Rejected pieces':'Authorised extra pieces'}<input aria-label={key==='quantity'?'Good pieces':key==='rejects'?'Rejected pieces':'Authorised extra pieces'} type="number" min="0" step="1" value={work[key]} onChange={e=>setWork({...work,[key]:Number(e.target.value)})}/></label>)}<label>Work note / authorisation<input value={work.reason} onChange={e=>setWork({...work,reason:e.target.value})}/></label></div><button className="primary" disabled={busy}>Record work</button></form>}
      <details><summary>Work and handoff history</summary>{active.events.map(event=><p key={event.id}>{new Date(event.at).toLocaleString()} · {active.allocations.find(row=>row.key===event.allocationKey)?.orderNo} · {event.operation}: {event.quantity} good, {event.rejects} rejects, {event.extras} extras · {event.reason} · {event.actor}</p>)}{active.history.map((event,index)=><p key={index}>{new Date(event.at).toLocaleString()} · {event.action} · {event.actor}</p>)}</details></section>}
    </>}
  </section>;
}
