"use client";

import "./seiko-billing-stage2.css";
import "./seiko-billing-polish.css";

import { useCallback, useEffect, useRef, useState } from "react";
import type { SeikoOrder } from "./lib/order-domain";
import { packingQuantities } from "./lib/packing-label-model";
import { formatInr, orderReceiptDocument, paymentAppliedToInvoice, unappliedOrderPayment, billingStatus, documentTotals, invoiceOutstanding, validateBillingDocument, type SeikoBillingLine, type SeikoCommercialDocument, type SeikoDocumentKind, type SeikoPaymentRecord } from "./lib/seiko-billing";
import { billingPrintHtml, fitBillingCopies, type BillingCopies } from "./lib/seiko-billing-print";
import { ClientEditor } from "./seiko-client-directory";
import { newSeikoClient, requestSeikoClients, type SeikoClientRecord } from "./lib/seiko-clients";

type Ledger = { documents: SeikoCommercialDocument[]; payments: SeikoPaymentRecord[]; canManage: boolean };
type Props = { orders: SeikoOrder[]; legacyDocuments?: SeikoCommercialDocument[]; legacyPayments?: SeikoPaymentRecord[]; initialOrderId?: string; initialAction?: "payment" | "payments" | "invoice" | "quotation" | "challan" | null; onActionHandled?: () => void };
const money = formatInr;
const today = () => new Date().toLocaleDateString("en-CA");
const newLine = (): SeikoBillingLine => ({ id: crypto.randomUUID(), description: "", quantity: 1, unit: "pc", unitRate: 0, taxRate: 0, hsnSac: "" });
const supplierBlank = () => ({ name: "SEIKO Tailors", address: "", phone: "", gstin: "", bank: "", upi: "", paymentQr: "", showBank: false, showUpi: false, showQr: false });

export function SeikoBillingWorkspace({ orders, legacyDocuments = [], initialAction, initialOrderId = "", onActionHandled }: Props) {
  const [ledger, setLedger] = useState<Ledger>({ documents: [], payments: [], canManage: false });
  const [loaded, setLoaded] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [query, setQuery] = useState("");
  const [documentKind,setDocumentKind]=useState<"all"|SeikoDocumentKind>("all"); const [filter, setFilter] = useState(initialOrderId);
  const [creating, setCreating] = useState<SeikoDocumentKind | null>(() => initialAction === "invoice" || initialAction === "quotation" ? initialAction : initialAction === "challan" ? "delivery_challan" : null);
  const [selectedId, setSelectedId] = useState(""); const [paying, setPaying] = useState(initialAction === "payment"); const [amending, setAmending] = useState(false);
  const [receiptId, setReceiptId] = useState(""); const [copies, setCopies] = useState<BillingCopies>("both");
  const [paymentOrderId, setPaymentOrderId] = useState(initialAction === "payment" ? initialOrderId : "");
  const [paymentInvoiceId, setPaymentInvoiceId] = useState("");
  const [paymentSearch, setPaymentSearch] = useState("");
  const [view, setView] = useState<"invoices" | "payments">(initialAction === "payments" ? "payments" : "invoices");
  const [notice, setNotice] = useState("");
  const [clients, setClients] = useState<SeikoClientRecord[]>([]); const [clientBusy, setClientBusy] = useState(false); const [clientError, setClientError] = useState("");
  const frame = useRef<HTMLIFrameElement>(null); const pending = useRef(false);
  const request = useCallback(async (body: object) => {
    const response = await fetch("/api/erp/billing", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json();
    if (!response.ok || !result.ok) throw new Error(result.message || "Billing could not be loaded.");
    setLedger(result); setLoaded(true); return result as Ledger;
  }, []);
  const refresh = useCallback(async () => { if (pending.current) return; setBusy(true); setError(""); try { await request({ operation: "list" }); } catch (cause) { setError(String((cause as Error).message)); } finally { setBusy(false); } }, [request]);
  useEffect(() => { void request({ operation: "list" }).catch(cause => setError((cause as Error).message)); }, [request]);
  useEffect(() => { void requestSeikoClients({ operation: "list" }).then(result => setClients(result.clients)).catch(cause => setClientError((cause as Error).message)); }, []);
  useEffect(() => { if (initialAction) queueMicrotask(() => onActionHandled?.()); }, [initialAction, onActionHandled]);
  async function saveClient(client: SeikoClientRecord) { setClientBusy(true); setClientError(""); try { const result = await requestSeikoClients({ operation: "save", client }); setClients(result.clients); return result.clients.find(item => item.id === client.id) || result.clients.find(item => item.phone.replace(/\D/g, "") === client.phone.replace(/\D/g, "")); } catch (cause) { setClientError((cause as Error).message); } finally { setClientBusy(false); } }
  async function save(body: object, done: (next: Ledger) => void) {
    if (pending.current) return;
    pending.current = true; setBusy(true); setError("");
    try { const next = await request(body); done(next); } catch (cause) { setError((cause as Error).message); } finally { pending.current = false; setBusy(false); }
  }
  const receipt = ledger.payments.find(item => item.id === receiptId);
  const selected = receipt && !receipt.invoiceId ? orderReceiptDocument(receipt) : ledger.documents.find(item => item.id === selectedId);
  const paymentOrder = orders.find(item => item.orderId === paymentOrderId);
  const paymentInvoice = ledger.documents.find(item => item.id === paymentInvoiceId);
  const unpaid = ledger.documents.filter(item => item.kind === "invoice" && item.status !== "cancelled" && invoiceOutstanding(item, ledger.payments) > 0);
  const paymentOptions = unpaid.filter(item => (!initialOrderId || item.orderId === initialOrderId) && `${item.number} ${item.clientName} ${item.orderNo}`.toLowerCase().includes(paymentSearch.toLowerCase()));
  const visiblePayments = ledger.payments.filter(payment => {
    const invoice = ledger.documents.find(item => item.id === payment.invoiceId);
    return (!filter || payment.orderId === filter || invoice?.orderId === filter || payment.allocations?.some(allocation => ledger.documents.some(document => document.id === allocation.invoiceId && document.orderId === filter)) || (filter === "standalone" && !payment.orderId && !invoice?.orderId)) && `${payment.receiptNumber} ${payment.reference} ${payment.mode} ${payment.clientName || invoice?.clientName || ""} ${invoice?.number || ""} ${payment.orderNo || invoice?.orderNo || ""}`.toLowerCase().includes(query.toLowerCase());
  });
  function startPayment(invoiceId = "") { setPaymentOrderId(invoiceId ? "" : initialOrderId); setError(""); setNotice(""); setPaymentSearch(""); setPaymentInvoiceId(invoiceId); setPaying(true); }
  const visible = ledger.documents.filter(item => (!filter || item.orderId === filter || (filter === "standalone" && !item.orderId)) && `${item.number} ${item.clientName} ${item.orderNo}`.toLowerCase().includes(query.toLowerCase()));
  const visibleDocuments=visible.filter(item=>documentKind==="all"||item.kind===documentKind);
  const invoices = visible.filter(item => item.kind === "invoice" && item.status !== "cancelled");
  return <div className="phase2Workspace seikoBillingWorkspace">
    <div className="phase2Actions" aria-label="Billing views and quick actions">
      <button className={view === "invoices" ? "primary" : "secondary"} aria-pressed={view === "invoices"} onClick={() => setView("invoices")}>Invoices & documents</button>
      <button className={view === "payments" ? "primary" : "secondary"} aria-pressed={view === "payments"} onClick={() => setView("payments")}>Payments & receipts</button>
      <button className="primary" disabled={!ledger.canManage || busy} onClick={() => startPayment()}>Record payment</button>
    </div>
    {notice && <p role="status">{notice}</p>}
    <div className="phase2Toolbar"><label>Find bill<input placeholder="Invoice, client or order" value={query} onChange={event => setQuery(event.target.value)}/></label><label>Source<select aria-label="Billing source" value={filter} onChange={event => setFilter(event.target.value)}><option value="">All bills</option><option value="standalone">Standalone bills</option>{orders.map(order => <option key={order.orderId} value={order.orderId}>{order.details.orderNo} · {order.details.clientName}</option>)}</select></label><div className="phase2Actions"><button className="secondary" disabled={busy} onClick={() => void refresh()}>Refresh</button><a className="secondary billingRecoveryLink" href="/backups">Backup & recovery</a><button className="primary" disabled={!ledger.canManage || busy} onClick={() => setCreating("invoice")}>+ Invoice</button><button className="secondary" disabled={!ledger.canManage || busy} onClick={() => setCreating("quotation")}>+ Quotation</button><button className="secondary" disabled={!ledger.canManage || busy} onClick={() => setCreating("delivery_challan")}>+ Challan</button></div></div>
    <p role="status">{busy ? "Saving / loading billing…" : loaded ? "Invoices and payments are saved to SEIKO’s shared database." : "Connecting to billing…"}</p>
    {error && <p role="alert" className="billingError">{error}</p>}
    {!!legacyDocuments.length && <p>There are {legacyDocuments.length} older browser-only documents. Use the local recovery copy in Backup & recovery to preserve them; they have not been reissued as new invoices.</p>}
    <p className="billingMetricScope">Totals for the selected source and search. Received includes invoice payments and order advances; invoice balance excludes unused advances. Document-type buttons filter the list below.</p><div className="phase2Metrics"><article><small>INVOICED</small><strong>{money(invoices.reduce((sum, item) => sum + documentTotals(item).total, 0))}</strong></article><article><small>RECEIVED</small><strong>{money(visiblePayments.reduce((sum, item) => sum + item.amount, 0))}</strong></article><article><small>INVOICE BALANCE</small><strong>{money(invoices.reduce((sum, item) => sum + invoiceOutstanding(item, ledger.payments), 0))}</strong></article><article><small>UNUSED ADVANCE</small><strong>{money(visiblePayments.reduce((sum, item) => sum + unappliedOrderPayment(item), 0))}</strong></article><article><small>DOCUMENTS</small><strong>{visible.length}</strong></article></div>
    {view === "invoices" && <div className="billingDocumentFilters" aria-label="Document type">{([["all","All documents"],["invoice","Invoices"],["quotation","Quotations"],["delivery_challan","Challans"]] as const).map(([kind,label])=><button type="button" key={kind} className={documentKind===kind?"primary":"secondary"} aria-pressed={documentKind===kind} onClick={()=>setDocumentKind(kind)}>{label}</button>)}</div>}
    {view === "invoices" && <section className="phase2Table billingDocumentTable"><div className="phase2TableHead"><span>Document</span><span>Client / Order</span><span>Total</span><span>Status</span><span>Balance / Action</span></div>{visibleDocuments.map(item => <div className="phase2TableRow billingDocumentRow" key={item.id}><span><button type="button" className="billingRowLink" aria-label={`Open ${item.number} for ${item.clientName}`} onClick={() => { setSelectedId(item.id); setReceiptId(""); }}><b>{item.number}</b></button><small>{item.issueDate} · {item.kind.replace("_", " ")}</small></span><span>{item.clientName}<small>{item.orderNo || "Standalone bill"}</small></span><span>{item.kind==="delivery_challan"&&item.taxMode==="non_gst"&&!item.showMonetaryValues?"Not priced":money(documentTotals(item).total)}</span><span><span className={`billingStatusBadge billingStatus-${item.kind==="invoice"&&item.status!=="cancelled"&&documentTotals(item).total===0?"zero":billingStatus(item,ledger.payments)}`}>{item.kind==="invoice"&&item.status!=="cancelled"&&documentTotals(item).total===0?"Zero amount":billingStatus(item, ledger.payments).replace("_", " ")}</span></span><span className="billingRowAction"><b>{item.kind === "invoice" ? money(invoiceOutstanding(item, ledger.payments)) : "—"}</b>{item.kind === "invoice" && item.status !== "cancelled" && invoiceOutstanding(item, ledger.payments) > 0 && <button className="primary" disabled={!ledger.canManage || busy} onClick={() => startPayment(item.id)}>Record payment</button>}<details className="billingDocumentMenu" onToggle={event=>{
      const menu=event.currentTarget;if(!menu.open)return;
      document.querySelectorAll<HTMLDetailsElement>(".billingDocumentMenu[open]").forEach(other=>{if(other!==menu)other.open=false;});
      const anchor=menu.querySelector("summary")!.getBoundingClientRect();const panel=menu.querySelector<HTMLElement>("div")!;
      const width=Math.min(250,window.innerWidth-24);panel.style.position="fixed";panel.style.width=`${width}px`;panel.style.maxHeight=`${window.innerHeight-24}px`;panel.style.overflowY="auto";
      panel.style.left=`${Math.max(12,Math.min(window.innerWidth-width-12,anchor.right-width))}px`;panel.style.right="auto";
      panel.style.top=`${Math.max(12,Math.min(window.innerHeight-panel.getBoundingClientRect().height-12,anchor.bottom+5))}px`;
    }}><summary aria-label={`Actions for ${item.number}`}>•••</summary><div onClickCapture={event=>{if((event.target as Element).closest("button"))event.currentTarget.closest("details")!.open=false;}}><b>{item.number}</b><button type="button" onClick={()=>{setSelectedId(item.id);setReceiptId("");}}>Open / print document</button>{ledger.canManage&&item.status!=="cancelled"&&<button type="button" onClick={()=>{setSelectedId(item.id);setReceiptId("");setAmending(true);}}>Amend document</button>}{item.kind==="invoice"&&item.status!=="cancelled"&&invoiceOutstanding(item,ledger.payments)>0&&<button type="button" disabled={!ledger.canManage||busy} onClick={()=>startPayment(item.id)}>Record payment</button>}{item.kind==="invoice"&&<button type="button" onClick={()=>{setSelectedId(item.id);setReceiptId("");}}>View invoice / receipts</button>}</div></details></span></div>)}{loaded && !visibleDocuments.length && <p className="phase2Empty">No bills match this view. Create an invoice from an order or start a standalone bill.</p>}</section>}
    {view === "payments" && <section className="phase2Table" aria-label="Payment history"><div className="phase2TableHead"><span>Receipt / date</span><span>Client / order</span><span>Received</span><span>Method / reference</span><span>Actions</span></div>{visiblePayments.map(payment => { const invoice = ledger.documents.find(item => item.id === payment.invoiceId); return <div className="phase2TableRow" key={payment.id}><span><b>{payment.receiptNumber}</b><small>{payment.date}</small></span><span>{payment.clientName || invoice?.clientName}<small>{payment.orderNo || invoice?.number || payment.orderId}</small></span><span>{money(payment.amount)}{unappliedOrderPayment(payment) > 0 && <small>Unused advance: {money(unappliedOrderPayment(payment))}</small>}</span><span>{payment.mode}<small>{payment.reference || "—"}</small></span><span><button className="secondary" onClick={() => { setSelectedId(invoice?.id || ""); setReceiptId(payment.id); }}>Receipt</button>{invoice && <button className="secondary" onClick={() => { setSelectedId(invoice.id); setReceiptId(""); }}>Updated invoice</button>}</span></div>; })}{loaded && !visiblePayments.length && <p className="phase2Empty">No payments match this view.</p>}</section>}
    {paying && !paymentInvoice && !paymentOrder && <div className="phase2Scrim billingFormScrim"><section className="phase2Editor" role="dialog" aria-modal="true" aria-label="Choose order or invoice for payment"><header><h2>Record payment</h2><button className="secondary" onClick={() => setPaying(false)}>Close</button></header><div className="phase2EditorBody" style={{ display: "block" }}><label>Find client, invoice or order<input value={paymentSearch} onChange={event => setPaymentSearch(event.target.value)} placeholder="Search orders or unpaid invoices"/></label><h3>Order advance / part payment</h3><p>No invoice is required. Payments apply to the oldest invoices for that order; any excess remains an advance.</p>{orders.filter(order => order.status !== "Cancelled" && (order.details.clientName + " " + order.details.orderNo).toLowerCase().includes(paymentSearch.toLowerCase())).map(order => <p key={order.orderId}><button className="secondary" onClick={() => setPaymentOrderId(order.orderId)}>{order.details.clientName} · {order.details.orderNo} · Received {money(ledger.payments.filter(p => p.orderId === order.orderId).reduce((sum,p) => sum + p.amount, 0))}</button></p>)}<h3>Pay an invoice</h3>{paymentOptions.map(invoice => <p key={invoice.id}><button className="secondary" onClick={() => setPaymentInvoiceId(invoice.id)}>{invoice.clientName} · {invoice.number} · Balance {money(invoiceOutstanding(invoice, ledger.payments))}</button></p>)}{!paymentOptions.length && <p>No unpaid invoices match.</p>}</div></section></div>}
    {creating && <BillEditor kind={creating} orders={orders} clients={clients} initialOrderId={filter} supplier={ledger.documents.find(item => item.supplier)?.supplier} busy={busy || clientBusy} error={error || clientError} onCreateClient={saveClient} onCancel={() => setCreating(null)} onSave={document => void save({ operation: "create", document }, () => { setCreating(null); setSelectedId(document.id); setReceiptId(""); })}/>}
    {amending && selected && <BillEditor kind={selected.kind} orders={orders} clients={clients} initialOrderId={selected.orderId} initialDocument={selected} supplier={selected.supplier} busy={busy || clientBusy} error={error || clientError} onCreateClient={saveClient} onCancel={() => setAmending(false)} onSave={document => void save({ operation: "amend", document }, () => { setAmending(false); setNotice("Document amended. The document number has been preserved."); })}/>}
    {selected && !amending && <div className="phase2Scrim"><section className="billingPreview" role="dialog" aria-modal="true" aria-label={selected.number}><header><h2>{receipt ? receipt.receiptNumber : selected.number} · {selected.clientName}</h2><button className="secondary" onClick={() => { setSelectedId(""); setReceiptId(""); setPaying(false); }}>Close</button></header><div className="billingPreviewTools"><label>Print copies<select value={copies} onChange={event => setCopies(event.target.value as BillingCopies)}><option value="both">All standard copies · one A4 when they fit</option><option value="separate">All standard copies · separate A4 pages</option><option value="customer">Recipient / payer copy only</option><option value="supplier">Office / supplier copy only</option></select></label><button className="primary" onClick={async () => { if (frame.current?.contentWindow) { await frame.current.contentDocument?.fonts.ready; fitBillingCopies(frame.current, copies); frame.current.contentWindow.focus(); frame.current.contentWindow.print(); } }}>Print / Save PDF</button>{ledger.canManage && !receipt && <button className="secondary" onClick={() => setAmending(true)}>Amend document</button>}{selected.kind === "invoice" && <button className="secondary" disabled={busy || !ledger.canManage || invoiceOutstanding(selected, ledger.payments) <= 0} onClick={() => startPayment(selected.id)}>Record payment</button>}{selected.kind === "invoice" && <button className="secondary" onClick={() => setReceiptId("")}>Updated invoice</button>}</div><p>Print on A4 at 100%, with browser headers and footers off. Long copies continue on additional pages.</p><div className="billingReceiptList">{ledger.payments.filter(item => paymentAppliedToInvoice(item, selected.id) > 0).map(item => <button className="secondary" key={item.id} onClick={() => setReceiptId(item.id)}>{item.receiptNumber} · {money(item.amount)} · {item.date}</button>)}</div><iframe ref={frame} title="Billing print preview" srcDoc={billingPrintHtml(selected, ledger.payments, copies, receipt)} onLoad={() => { if (frame.current) fitBillingCopies(frame.current, copies); }}/></section></div>}
    {paying && paymentOrder && <PaymentForm key={paymentOrder.orderId} order={paymentOrder} payments={ledger.payments} busy={busy} error={error} onCancel={() => setPaying(false)} onSave={payment => void save({ operation: "payment", payment }, () => { setPaying(false); setPaymentOrderId(""); setSelectedId(""); setReceiptId(payment.id); setNotice("Order payment recorded. Your receipt is ready to print."); })}/>}
    {paying && paymentInvoice && <PaymentForm key={paymentInvoice.id} invoice={paymentInvoice} payments={ledger.payments} busy={busy} error={error} onCancel={() => setPaying(false)} onSave={payment => void save({ operation: "payment", payment }, () => { setPaying(false); setPaymentInvoiceId(""); setSelectedId(payment.invoiceId); setReceiptId(payment.id); setNotice("Payment recorded. The receipt and updated invoice are ready to print."); })}/>}
  </div>;
}

function BillEditor({ kind, orders, clients, initialOrderId, initialDocument, supplier, busy, error, onCreateClient, onCancel, onSave }: { kind: SeikoDocumentKind; orders: SeikoOrder[]; clients: SeikoClientRecord[]; initialOrderId: string; initialDocument?: SeikoCommercialDocument; supplier?: SeikoCommercialDocument["supplier"]; busy: boolean; error: string; onCreateClient: (client: SeikoClientRecord) => Promise<SeikoClientRecord | undefined>; onCancel: () => void; onSave: (value: SeikoCommercialDocument) => void }) {
  const makeDraft = (orderId: string): SeikoCommercialDocument => {
    const order = orders.find(item => item.orderId === orderId); const quantities = order ? packingQuantities(order) : null;
    const lines = order?.products.map(product => ({ ...newLine(), description: product.name, quantity: product.quantityMode === "order_total" ? product.orderTotal : [...quantities!.values()].reduce((sum, values) => sum + (values[product.id] || 0), 0) })).filter(line => line.quantity > 0) || [];
    return { id: crypto.randomUUID(), kind, number: "Assigned on save", orderId: order?.orderId || "", orderNo: order?.details.orderNo || "", clientName: order?.details.clientName || "", clientPhone: order?.details.contactNumber || "", clientAddress: order?.details.billTo || "", clientDeliveryAddress: "", clientGstin: "", supplier: supplier || supplierBlank(), issueDate: today(), dueDate: "", taxMode: "non_gst", taxTreatment: "intra_state", placeOfSupply: "", reverseCharge: false, supplyType: "goods", showMonetaryValues: kind !== "delivery_challan", dispatch: { dispatchDate: today(), transporter: "", vehicleNo: "", eWayBillNo: "", packages: "", returnable: false }, lines: lines.length ? lines : [newLine()], notes: "", status: "issued", createdAt: "", updatedAt: "" };
  };
  const [draft, setDraft] = useState(() => initialDocument ? structuredClone(initialDocument) : makeDraft(initialOrderId)); const [problem, setProblem] = useState(""); const [addingClient, setAddingClient] = useState(false);
  const update = (patch: Partial<SeikoCommercialDocument>) => setDraft({ ...draft, ...patch });
  const applyClient = (client: SeikoClientRecord) => update({ clientId: client.id, clientType: client.type, clientName: client.name, clientContactPerson: client.contactPerson, clientPhone: client.phone, clientEmail: client.email, clientAddress: client.billingAddress, clientGstin: client.gstin });
  const chooseClient = (id: string) => { const client = clients.find(item => item.id === id); if (!client) { update({ clientId: "" }); return; } applyClient(client); };
  const lineUpdate = (id: string, patch: Partial<SeikoBillingLine>) => update({ lines: draft.lines.map(line => line.id === id ? { ...line, ...patch } : line) });
  return <BillingModal title={`${initialDocument ? "Amend" : "New"} ${kind.replace("_", " ")}`} busy={busy} onCancel={onCancel} onSave={() => { const validation = validateBillingDocument(draft); setProblem(validation); if (!validation) onSave(draft); }}>
    {!initialDocument && <><label>Bill source<select aria-label="Bill source" value={draft.orderId} onChange={event => { setDraft(makeDraft(event.target.value)); setProblem(""); }}><option value="">Standalone bill · no order</option>{orders.filter(order => !order.archived && order.status !== "Cancelled").map(order => <option key={order.orderId} value={order.orderId}>{order.details.orderNo} · {order.details.clientName}</option>)}</select></label><p>Choosing another source starts a fresh draft. Order quantities exclude held records; review rates before saving.</p></>}{initialDocument && <p className="billingFull"><b>{initialDocument.number}</b> · Amendments preserve this number and are marked with a revision.</p>}
    <label className="billingFull">Saved client<select aria-label="Saved client" value={draft.clientId || ""} onChange={event => chooseClient(event.target.value)}><option value="">Enter details manually</option>{clients.filter(client => !client.archived).map(client => <option value={client.id} key={client.id}>{client.name} · {client.phone}</option>)}</select></label>
    <button type="button" className="secondary billingFull" onClick={() => setAddingClient(true)}>+ Create client here</button>
    {addingClient && <ClientEditor compact client={newSeikoClient()} busy={busy} error={error} onCancel={() => setAddingClient(false)} onSave={async client => { const saved = await onCreateClient(client); if (saved) { applyClient(saved); setAddingClient(false); } }}/>} {/* inline client creation */}
    <Field label="Client name *" value={draft.clientName} onChange={clientName => update({ clientName })}/><Field label="Client phone *" value={draft.clientPhone || ""} onChange={clientPhone => update({ clientPhone })}/><Field label="Billing address" value={draft.clientAddress || ""} onChange={clientAddress => update({ clientAddress })}/><Field label="Delivery address" value={draft.clientDeliveryAddress || ""} onChange={clientDeliveryAddress => update({ clientDeliveryAddress })}/><Field label="Client GSTIN" value={draft.clientGstin || ""} onChange={clientGstin => update({ clientGstin })}/><Field label="Issue date" type="date" value={draft.issueDate} onChange={issueDate => update({ issueDate })}/>{kind !== "delivery_challan" && <Field label="Due date" type="date" value={draft.dueDate || ""} onChange={dueDate => update({ dueDate })}/>}
    <details className="billingFull" open><summary>SEIKO business & payment details</summary><div className="billingFields"><Field label="Business name *" value={draft.supplier!.name} onChange={name => update({ supplier: { ...draft.supplier!, name } })}/><Field label="Business phone" value={draft.supplier!.phone} onChange={phone => update({ supplier: { ...draft.supplier!, phone } })}/><Field label="Business address" value={draft.supplier!.address} onChange={address => update({ supplier: { ...draft.supplier!, address } })}/><Field label="Supplier GSTIN" value={draft.supplier!.gstin} onChange={gstin => update({ supplier: { ...draft.supplier!, gstin } })}/>{kind !== "delivery_challan" && <PaymentDetailsEditor supplier={draft.supplier!} onChange={supplier => update({ supplier })}/>}</div></details>
    <label>Document tax mode<select value={draft.taxMode} onChange={event => update({ taxMode: event.target.value as "gst" | "non_gst", showMonetaryValues: event.target.value === "gst" ? true : draft.showMonetaryValues })}><option value="non_gst">Non-GST document</option><option value="gst">GST document</option></select></label>{draft.taxMode === "gst" && <><label>Tax treatment<select value={draft.taxTreatment} onChange={event => update({ taxTreatment: event.target.value as "intra_state" | "inter_state" })}><option value="intra_state">CGST + SGST</option><option value="inter_state">IGST</option></select></label><Field label="Place of supply (State and code) *" value={draft.placeOfSupply || ""} onChange={placeOfSupply => update({ placeOfSupply })}/><label className="phase2Check"><input type="checkbox" checked={Boolean(draft.reverseCharge)} onChange={event => update({ reverseCharge: event.target.checked })}/>Tax payable under reverse charge</label></>}{kind === "delivery_challan" && draft.taxMode === "non_gst" && <label className="phase2Check billingFull"><input type="checkbox" checked={Boolean(draft.showMonetaryValues)} onChange={event => update({ showMonetaryValues: event.target.checked })}/>Show rates, amounts and total</label>}
    {kind === "delivery_challan" && <details className="billingFull" open><summary>Dispatch and transport details</summary><div className="billingFields"><Field label="Dispatch date" type="date" value={draft.dispatch?.dispatchDate || ""} onChange={dispatchDate => update({ dispatch: { ...draft.dispatch, dispatchDate } })}/><Field label="Transporter" value={draft.dispatch?.transporter || ""} onChange={transporter => update({ dispatch: { ...draft.dispatch, transporter } })}/><Field label="Vehicle number" value={draft.dispatch?.vehicleNo || ""} onChange={vehicleNo => update({ dispatch: { ...draft.dispatch, vehicleNo } })}/><Field label="E-way bill number" value={draft.dispatch?.eWayBillNo || ""} onChange={eWayBillNo => update({ dispatch: { ...draft.dispatch, eWayBillNo } })}/><Field label="Packages / cartons" value={draft.dispatch?.packages || ""} onChange={packages => update({ dispatch: { ...draft.dispatch, packages } })}/><label className="phase2Check"><input type="checkbox" checked={Boolean(draft.dispatch?.returnable)} onChange={event => update({ dispatch: { ...draft.dispatch, returnable: event.target.checked } })}/>Returnable goods</label></div></details>}
    <div className="billingFull">{draft.lines.map((line,index) => <fieldset className={`billingLine ${kind === "delivery_challan" ? "challanLine" : ""}`} key={line.id}><legend>Item {index + 1}</legend><Field label="Description" value={line.description} onChange={description => lineUpdate(line.id, { description })}/>{draft.taxMode === "gst" && <Field label="HSN/SAC *" value={line.hsnSac || ""} onChange={hsnSac => lineUpdate(line.id, { hsnSac })}/>}<Field label="Quantity" type="number" value={String(line.quantity)} onChange={value => lineUpdate(line.id, { quantity: Number(value) })}/><Field label="Unit" value={line.unit} onChange={unit => lineUpdate(line.id, { unit })}/>{(kind !== "delivery_challan" || draft.taxMode === "gst" || draft.showMonetaryValues) && <Field label="Rate ₹" type="number" value={String(line.unitRate)} onChange={value => lineUpdate(line.id, { unitRate: Number(value) })}/>} {draft.taxMode === "gst" && <Field label="GST %" type="number" value={String(line.taxRate)} onChange={value => lineUpdate(line.id, { taxRate: Number(value) })}/>}<button type="button" className="secondary" disabled={draft.lines.length === 1} onClick={() => update({ lines: draft.lines.filter(item => item.id !== line.id) })}>Remove item</button></fieldset>)}<button type="button" className="secondary" onClick={() => update({ lines: [...draft.lines, newLine()] })}>+ Item / service</button></div>
    <label className="billingFull">Notes{kind !== "delivery_challan" ? " / payment terms" : " / dispatch instructions"}<textarea value={draft.notes} onChange={event => update({ notes: event.target.value })}/></label>{(kind !== "delivery_challan" || draft.taxMode === "gst" || draft.showMonetaryValues) && <p>Total: <b>{money(documentTotals(draft).total)}</b> · Document number assigned when saved.</p>}{(problem || error) && <p role="alert" className="billingError">{problem || error}</p>}
  </BillingModal>;
}

function PaymentForm({ invoice, order, payments, busy, error, onCancel, onSave }: { invoice?: SeikoCommercialDocument; order?: SeikoOrder; payments: SeikoPaymentRecord[]; busy: boolean; error: string; onCancel: () => void; onSave: (payment: SeikoPaymentRecord) => void }) {
  const balance = invoice ? invoiceOutstanding(invoice, payments) : undefined;
  const [payment, setPayment] = useState<SeikoPaymentRecord>(() => ({ id: crypto.randomUUID(), invoiceId: invoice?.id || "", orderId: order?.orderId || invoice?.orderId || "", receiptNumber: "", date: today(), amount: balance || 0, mode: "Bank transfer", reference: "", notes: "", createdAt: "" }));
  const [problem, setProblem] = useState("");
  return <BillingModal title={`Record payment · ${invoice?.number || order?.details.orderNo}`} busy={busy} onCancel={onCancel} onSave={() => { if (!Number.isFinite(payment.amount) || payment.amount <= 0 || (balance != null && payment.amount > balance)) { setProblem("Enter a positive payment no greater than the balance."); return; } onSave(payment); }}>{balance != null ? <p>Invoice balance: <b>{money(balance)}</b>. A numbered receipt will be created.</p> : <p>{order?.details.clientName} · Record an advance or part payment. A receipt will be created without issuing an invoice. Any unused amount remains an advance.</p>}<Field label="Amount received ₹" type="number" value={String(payment.amount)} onChange={value => setPayment({ ...payment, amount: Number(value) })}/><Field label="Payment date" type="date" value={payment.date} onChange={date => setPayment({ ...payment, date })}/><label>Payment mode<select value={payment.mode} onChange={event => setPayment({ ...payment, mode: event.target.value })}>{["Bank transfer", "UPI", "Cash", "Cheque", "Card", "Other"].map(value => <option key={value}>{value}</option>)}</select></label><Field label="Reference / transaction ID" value={payment.reference} onChange={reference => setPayment({ ...payment, reference })}/><Field label="Notes" value={payment.notes} onChange={notes => setPayment({ ...payment, notes })}/>{(problem || error) && <p className="billingError" role="alert">{problem || error}</p>}</BillingModal>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label>{label}<input type={type} step={type === "number" ? "0.01" : undefined} min={type === "number" ? "0" : undefined} value={value} onChange={event => onChange(event.target.value)}/></label>; }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="billingFull">{label}<textarea rows={5} value={value} onChange={event => onChange(event.target.value)} onKeyDown={event => event.stopPropagation()}/></label>; }
function PaymentDetailsEditor({ supplier, onChange }: { supplier: NonNullable<SeikoCommercialDocument["supplier"]>; onChange: (supplier: NonNullable<SeikoCommercialDocument["supplier"]>) => void }) {
  const uploadQr = (file?: File) => { if (!file) return; if (file.size > 100 * 1024) { window.alert("Use a QR image smaller than 100 KB."); return; } const reader = new FileReader(); reader.onload = () => onChange({ ...supplier, paymentQr: String(reader.result || ""), showQr: true }); reader.readAsDataURL(file); };
  return <section className="billingPaymentSetup"><h3>Payment information on this document</h3><label className="phase2Check"><input type="checkbox" checked={Boolean(supplier.showBank)} onChange={event => onChange({ ...supplier, showBank: event.target.checked })}/>Include bank details</label>{supplier.showBank && <TextArea label="Bank account details (one detail per line)" value={supplier.bank} onChange={bank => onChange({ ...supplier, bank })}/>}<label className="phase2Check"><input type="checkbox" checked={Boolean(supplier.showUpi)} onChange={event => onChange({ ...supplier, showUpi: event.target.checked })}/>Include UPI</label>{supplier.showUpi && <Field label="UPI ID" value={supplier.upi || ""} onChange={upi => onChange({ ...supplier, upi })}/>}<label className="phase2Check"><input type="checkbox" checked={Boolean(supplier.showQr)} onChange={event => onChange({ ...supplier, showQr: event.target.checked })}/>Include payment QR scanner</label>{supplier.showQr && <label>Payment QR image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event => uploadQr(event.target.files?.[0])}/>{supplier.paymentQr && <span className="billingQrReady">QR image ready · <button type="button" className="textButton" onClick={() => onChange({ ...supplier, paymentQr: "", showQr: false })}>Remove</button></span>}</label>}</section>;
}
function BillingModal({ title, busy, children, onCancel, onSave }: { title: string; busy: boolean; children: React.ReactNode; onCancel: () => void; onSave: () => void }) { return <div className="phase2Scrim billingFormScrim"><form className="phase2Editor" role="dialog" aria-modal="true" aria-label={title} onSubmit={event => { event.preventDefault(); if (!busy) onSave(); }}><header><h2>{title}</h2><button type="button" disabled={busy} onClick={onCancel} aria-label="Close">×</button></header><fieldset className="phase2EditorBody billingFormBody" disabled={busy}>{children}</fieldset><footer><button type="button" className="secondary" disabled={busy} onClick={onCancel}>Cancel</button><button type="submit" className="primary" disabled={busy}>{busy ? "Saving…" : "Save"}</button></footer></form></div>; }

