"use client";

import { useEffect, useRef, useState } from "react";
import type { SeikoOrder } from "./lib/order-domain";
import { packingQuantities } from "./lib/packing-label-model";
import { billingStatus, documentTotals, invoiceOutstanding, paymentsForInvoice, validateBillingDocument, type SeikoBillingLine, type SeikoCommercialDocument, type SeikoDocumentKind, type SeikoPaymentRecord } from "./lib/seiko-billing";
import { billingPrintHtml, fitBillingCopies, type BillingCopies } from "./lib/seiko-billing-print";

type Ledger = { documents: SeikoCommercialDocument[]; payments: SeikoPaymentRecord[]; canManage: boolean };
type Props = { orders: SeikoOrder[]; legacyDocuments?: SeikoCommercialDocument[]; legacyPayments?: SeikoPaymentRecord[] };
const money = (n: number) => `₹${n.toFixed(2)}`;
const today = () => new Date().toLocaleDateString("en-CA");
const newLine = (): SeikoBillingLine => ({ id: crypto.randomUUID(), description: "", quantity: 1, unit: "pc", unitRate: 0, taxRate: 0 });
const supplierBlank = () => ({ name: "SEIKO Tailors", address: "", phone: "", gstin: "", bank: "" });

export function SeikoBillingWorkspace({ orders, legacyDocuments = [], legacyPayments = [] }: Props) {
  const [ledger, setLedger] = useState<Ledger>({ documents: [], payments: [], canManage: false });
  const [loaded, setLoaded] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("");
  const [creating, setCreating] = useState<SeikoDocumentKind | null>(null);
  const [selectedId, setSelectedId] = useState(""); const [paying, setPaying] = useState(false);
  const [receiptId, setReceiptId] = useState(""); const [copies, setCopies] = useState<BillingCopies>("both");
  const frame = useRef<HTMLIFrameElement>(null); const pending = useRef(false);
  async function request(body: object) {
    const response = await fetch("/api/erp/billing", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json();
    if (!response.ok || !result.ok) throw new Error(result.message || "Billing could not be loaded.");
    setLedger(result); setLoaded(true); return result as Ledger;
  }
  async function refresh() { if (pending.current) return; setBusy(true); setError(""); try { await request({ operation: "list" }); } catch (cause) { setError(String((cause as Error).message)); } finally { setBusy(false); } }
  useEffect(() => { void refresh(); }, []);
  async function save(body: object, done: (next: Ledger) => void) {
    if (pending.current) return;
    pending.current = true; setBusy(true); setError("");
    try { const next = await request(body); done(next); } catch (cause) { setError((cause as Error).message); } finally { pending.current = false; setBusy(false); }
  }
  const selected = ledger.documents.find(item => item.id === selectedId);
  const receipt = ledger.payments.find(item => item.id === receiptId && item.invoiceId === selectedId);
  const visible = ledger.documents.filter(item => (!filter || item.orderId === filter || (filter === "standalone" && !item.orderId)) && `${item.number} ${item.clientName} ${item.orderNo}`.toLowerCase().includes(query.toLowerCase()));
  const invoices = visible.filter(item => item.kind === "invoice" && item.status !== "cancelled");
  function backup() { const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), ...ledger, legacyDocuments, legacyPayments }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `seiko-billing-${today()}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <div className="phase2Workspace seikoBillingWorkspace">
    <div className="phase2Toolbar"><label>Find bill<input placeholder="Invoice, client or order" value={query} onChange={event => setQuery(event.target.value)}/></label><label>Source<select value={filter} onChange={event => setFilter(event.target.value)}><option value="">All bills</option><option value="standalone">Standalone bills</option>{orders.map(order => <option key={order.orderId} value={order.orderId}>{order.details.orderNo} · {order.details.clientName}</option>)}</select></label><div className="phase2Actions"><button className="secondary" disabled={busy} onClick={() => void refresh()}>Refresh</button><button className="secondary" disabled={!loaded} onClick={backup}>Export backup</button><button className="primary" disabled={!ledger.canManage || busy} onClick={() => setCreating("invoice")}>+ Invoice</button><button className="secondary" disabled={!ledger.canManage || busy} onClick={() => setCreating("quotation")}>+ Quotation</button><button className="secondary" disabled={!ledger.canManage || busy} onClick={() => setCreating("delivery_challan")}>+ Challan</button></div></div>
    <p role="status">{busy ? "Saving / loading billing…" : loaded ? "Invoices and payments are saved to SEIKO’s shared database." : "Connecting to billing…"}</p>
    {error && <p role="alert" className="billingError">{error}</p>}
    {!!legacyDocuments.length && <p>There are {legacyDocuments.length} older browser-only documents. They are preserved in your backup export; they have not been reissued as new invoices.</p>}
    <div className="phase2Metrics"><article><small>INVOICED</small><strong>{money(invoices.reduce((sum, item) => sum + documentTotals(item).total, 0))}</strong></article><article><small>RECEIVED</small><strong>{money(invoices.reduce((sum, item) => sum + paymentsForInvoice(ledger.payments, item.id), 0))}</strong></article><article><small>OUTSTANDING</small><strong>{money(invoices.reduce((sum, item) => sum + invoiceOutstanding(item, ledger.payments), 0))}</strong></article><article><small>DOCUMENTS</small><strong>{visible.length}</strong></article></div>
    <section className="phase2Table"><div className="phase2TableHead"><span>Document</span><span>Client / Order</span><span>Total</span><span>Status</span><span>Balance / Open</span></div>{visible.map(item => <div className="phase2TableRow" key={item.id}><span><b>{item.number}</b><small>{item.issueDate} · {item.kind.replace("_", " ")}</small></span><span>{item.clientName}<small>{item.orderNo || "Standalone bill"}</small></span><span>{money(documentTotals(item).total)}</span><span>{billingStatus(item, ledger.payments).replace("_", " ")}</span><span>{item.kind === "invoice" && money(invoiceOutstanding(item, ledger.payments))} <button className="secondary" onClick={() => { setSelectedId(item.id); setReceiptId(""); }}>Open</button></span></div>)}{loaded && !visible.length && <p className="phase2Empty">No bills match this view. Create an invoice from an order or start a standalone bill.</p>}</section>
    {creating && <BillEditor kind={creating} orders={orders} initialOrderId={filter} supplier={ledger.documents.find(item => item.supplier)?.supplier} busy={busy} error={error} onCancel={() => setCreating(null)} onSave={document => void save({ operation: "create", document }, () => { setCreating(null); setSelectedId(document.id); setReceiptId(""); })}/>}
    {selected && <div className="phase2Scrim"><section className="billingPreview" role="dialog" aria-modal="true" aria-label={selected.number}><header><h2>{receipt ? receipt.receiptNumber : selected.number} · {selected.clientName}</h2><button className="secondary" onClick={() => { setSelectedId(""); setPaying(false); }}>Close</button></header><div className="billingPreviewTools"><label>Print copies<select value={copies} onChange={event => setCopies(event.target.value as BillingCopies)}><option value="both">Customer + Supplier · one A4 when they fit</option><option value="separate">Customer + Supplier · separate A4 pages</option><option value="customer">Customer / Client copy only</option><option value="supplier">Supplier copy only</option></select></label><button className="primary" onClick={async () => { if (frame.current?.contentWindow) { await frame.current.contentDocument?.fonts.ready; fitBillingCopies(frame.current, copies); frame.current.contentWindow.focus(); frame.current.contentWindow.print(); } }}>Print / Save PDF</button>{selected.kind === "invoice" && <button className="secondary" disabled={busy || !ledger.canManage || invoiceOutstanding(selected, ledger.payments) <= 0} onClick={() => setPaying(true)}>Record payment</button>}<button className="secondary" onClick={() => setReceiptId("")}>Updated invoice</button></div><p>Print on A4 at 100%, with browser headers and footers off. Long copies continue on additional pages.</p><div className="billingReceiptList">{ledger.payments.filter(item => item.invoiceId === selected.id).map(item => <button className="secondary" key={item.id} onClick={() => setReceiptId(item.id)}>{item.receiptNumber} · {money(item.amount)} · {item.date}</button>)}</div><iframe ref={frame} title="Billing print preview" srcDoc={billingPrintHtml(selected, ledger.payments, copies, receipt)} onLoad={() => { if (frame.current) fitBillingCopies(frame.current, copies); }}/></section></div>}
    {paying && selected && <PaymentForm invoice={selected} payments={ledger.payments} busy={busy} error={error} onCancel={() => setPaying(false)} onSave={payment => void save({ operation: "payment", payment }, () => { setPaying(false); setReceiptId(payment.id); })}/>}
  </div>;
}

function BillEditor({ kind, orders, initialOrderId, supplier, busy, error, onCancel, onSave }: { kind: SeikoDocumentKind; orders: SeikoOrder[]; initialOrderId: string; supplier?: SeikoCommercialDocument["supplier"]; busy: boolean; error: string; onCancel: () => void; onSave: (value: SeikoCommercialDocument) => void }) {
  const makeDraft = (orderId: string): SeikoCommercialDocument => {
    const order = orders.find(item => item.orderId === orderId); const quantities = order ? packingQuantities(order) : null;
    const lines = order?.products.map(product => ({ ...newLine(), description: product.name, quantity: product.quantityMode === "order_total" ? product.orderTotal : [...quantities!.values()].reduce((sum, values) => sum + (values[product.id] || 0), 0) })).filter(line => line.quantity > 0) || [];
    return { id: crypto.randomUUID(), kind, number: "Assigned on save", orderId: order?.orderId || "", orderNo: order?.details.orderNo || "", clientName: order?.details.clientName || "", clientPhone: order?.details.contactNumber || "", clientAddress: order?.details.billTo || "", clientGstin: "", supplier: supplier || supplierBlank(), issueDate: today(), dueDate: "", taxMode: "non_gst", taxTreatment: "intra_state", lines: lines.length ? lines : [newLine()], notes: "", status: "issued", createdAt: "", updatedAt: "" };
  };
  const [draft, setDraft] = useState(() => makeDraft(initialOrderId)); const [problem, setProblem] = useState("");
  const update = (patch: Partial<SeikoCommercialDocument>) => setDraft({ ...draft, ...patch });
  const lineUpdate = (id: string, patch: Partial<SeikoBillingLine>) => update({ lines: draft.lines.map(line => line.id === id ? { ...line, ...patch } : line) });
  return <BillingModal title={`New ${kind.replace("_", " ")}`} busy={busy} onCancel={onCancel} onSave={() => { const validation = validateBillingDocument(draft); setProblem(validation); if (!validation) onSave(draft); }}>
    <label>Bill source<select value={draft.orderId} onChange={event => { setDraft(makeDraft(event.target.value)); setProblem(""); }}><option value="">Standalone bill · no order</option>{orders.filter(order => !order.archived && order.status !== "Cancelled").map(order => <option key={order.orderId} value={order.orderId}>{order.details.orderNo} · {order.details.clientName}</option>)}</select></label><p>Choosing another source starts a fresh draft. Order quantities exclude held records; review rates before saving.</p>
    <Field label="Client name *" value={draft.clientName} onChange={clientName => update({ clientName })}/><Field label="Client phone *" value={draft.clientPhone || ""} onChange={clientPhone => update({ clientPhone })}/><Field label="Billing address" value={draft.clientAddress || ""} onChange={clientAddress => update({ clientAddress })}/><Field label="Client GSTIN" value={draft.clientGstin || ""} onChange={clientGstin => update({ clientGstin })}/><Field label="Issue date" type="date" value={draft.issueDate} onChange={issueDate => update({ issueDate })}/><Field label="Due date" type="date" value={draft.dueDate || ""} onChange={dueDate => update({ dueDate })}/>
    <details className="billingFull"><summary>Supplier & payment details</summary><div className="billingFields">{([['name','Supplier name *'],['address','Supplier address'],['phone','Supplier phone'],['gstin','Supplier GSTIN'],['bank','Bank / UPI details']] as const).map(([key,label]) => <Field key={key} label={label} value={draft.supplier![key]} onChange={value => update({ supplier: { ...draft.supplier!, [key]: value } })}/>)}</div></details>
    <label>Tax mode<select value={draft.taxMode} onChange={event => update({ taxMode: event.target.value as "gst" | "non_gst" })}><option value="non_gst">Without GST</option><option value="gst">GST document</option></select></label>{draft.taxMode === "gst" && <label>Tax treatment<select value={draft.taxTreatment} onChange={event => update({ taxTreatment: event.target.value as "intra_state" | "inter_state" })}><option value="intra_state">CGST + SGST</option><option value="inter_state">IGST</option></select></label>}
    <div className="billingFull">{draft.lines.map((line,index) => <fieldset className="billingLine" key={line.id}><legend>Item {index + 1}</legend><Field label="Description" value={line.description} onChange={description => lineUpdate(line.id, { description })}/><Field label="Quantity" type="number" value={String(line.quantity)} onChange={value => lineUpdate(line.id, { quantity: Number(value) })}/><Field label="Unit" value={line.unit} onChange={unit => lineUpdate(line.id, { unit })}/><Field label="Rate ₹" type="number" value={String(line.unitRate)} onChange={value => lineUpdate(line.id, { unitRate: Number(value) })}/>{draft.taxMode === "gst" && <Field label="GST %" type="number" value={String(line.taxRate)} onChange={value => lineUpdate(line.id, { taxRate: Number(value) })}/>}<button type="button" className="secondary" disabled={draft.lines.length === 1} onClick={() => update({ lines: draft.lines.filter(item => item.id !== line.id) })}>Remove item</button></fieldset>)}<button type="button" className="secondary" onClick={() => update({ lines: [...draft.lines, newLine()] })}>+ Item / service</button></div>
    <label className="billingFull">Notes / payment terms<textarea value={draft.notes} onChange={event => update({ notes: event.target.value })}/></label><p>Total: <b>{money(documentTotals(draft).total)}</b> · Invoice number assigned when saved.</p>{(problem || error) && <p role="alert" className="billingError">{problem || error}</p>}
  </BillingModal>;
}

function PaymentForm({ invoice, payments, busy, error, onCancel, onSave }: { invoice: SeikoCommercialDocument; payments: SeikoPaymentRecord[]; busy: boolean; error: string; onCancel: () => void; onSave: (payment: SeikoPaymentRecord) => void }) {
  const balance = invoiceOutstanding(invoice, payments);
  const [payment, setPayment] = useState<SeikoPaymentRecord>(() => ({ id: crypto.randomUUID(), invoiceId: invoice.id, orderId: invoice.orderId, receiptNumber: "", date: today(), amount: balance, mode: "Bank transfer", reference: "", notes: "", createdAt: "" }));
  const [problem, setProblem] = useState("");
  return <BillingModal title={`Record payment · ${invoice.number}`} busy={busy} onCancel={onCancel} onSave={() => { if (!Number.isFinite(payment.amount) || payment.amount <= 0 || payment.amount > balance) { setProblem("Enter a positive payment no greater than the balance."); return; } onSave(payment); }}><p>Current balance: <b>{money(balance)}</b>. A numbered receipt will be created and the invoice balance updated.</p><Field label="Amount received ₹" type="number" value={String(payment.amount)} onChange={value => setPayment({ ...payment, amount: Number(value) })}/><Field label="Payment date" type="date" value={payment.date} onChange={date => setPayment({ ...payment, date })}/><label>Payment mode<select value={payment.mode} onChange={event => setPayment({ ...payment, mode: event.target.value })}>{["Bank transfer", "UPI", "Cash", "Cheque", "Card", "Other"].map(value => <option key={value}>{value}</option>)}</select></label><Field label="Reference / transaction ID" value={payment.reference} onChange={reference => setPayment({ ...payment, reference })}/><Field label="Notes" value={payment.notes} onChange={notes => setPayment({ ...payment, notes })}/>{(problem || error) && <p className="billingError" role="alert">{problem || error}</p>}</BillingModal>;
}

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label>{label}<input type={type} step={type === "number" ? "0.01" : undefined} min={type === "number" ? "0" : undefined} value={value} onChange={event => onChange(event.target.value)}/></label>; }
function BillingModal({ title, busy, children, onCancel, onSave }: { title: string; busy: boolean; children: React.ReactNode; onCancel: () => void; onSave: () => void }) { return <div className="phase2Scrim billingFormScrim"><form className="phase2Editor" role="dialog" aria-modal="true" aria-label={title} onSubmit={event => { event.preventDefault(); if (!busy) onSave(); }}><header><h2>{title}</h2><button type="button" disabled={busy} onClick={onCancel} aria-label="Close">×</button></header><fieldset className="phase2EditorBody billingFormBody" disabled={busy}>{children}</fieldset><footer><button type="button" className="secondary" disabled={busy} onClick={onCancel}>Cancel</button><button type="submit" className="primary" disabled={busy}>{busy ? "Saving…" : "Save"}</button></footer></form></div>; }
