"use client";

import { useEffect } from "react";
import { startDomEnhancement } from "./lib/dom-enhancement";

type ExtraKind = "text" | "sequence" | "qr" | "barcode";
type Extra = { id:string; kind:ExtraKind; value:string; x:number; y:number; w:number; h:number; font:number };

const LABEL_W = 50;
const LABEL_H = 25;

function clamp(value:number,min:number,max:number){return Math.min(max,Math.max(min,value));}
function currentBusiness(){return new URLSearchParams(location.search).get("business")||localStorage.getItem("jinam:selected-business")||"seiko";}
function currentOrder(){return new URLSearchParams(location.search).get("order")||"current";}
function extrasKey(){return `jinam:${currentBusiness()}:packing-extras:${currentOrder()}`;}
function readExtras():Extra[]{try{const value=JSON.parse(localStorage.getItem(extrasKey())||"[]");return Array.isArray(value)?value:[];}catch{return[];}}
function writeExtras(items:Extra[]){localStorage.setItem(extrasKey(),JSON.stringify(items));}
function setReactInput(input:HTMLInputElement,value:string){Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value")?.set?.call(input,value);input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));}
function labelText(label:HTMLLabelElement){return label.childNodes[0]?.textContent?.trim()||label.querySelector("span")?.textContent?.trim()||"";}
function inspectorInput(page:HTMLElement,names:string[]){return Array.from(page.querySelectorAll<HTMLLabelElement>(".packingInspectorBar label,.packingSelectedControls label")).find(label=>names.includes(labelText(label)))?.querySelector<HTMLInputElement>("input")||null;}
function selectedParts(page:HTMLElement){const canvas=page.querySelector<HTMLElement>(".packingCanvas");const selected=canvas?.querySelector<HTMLElement>(".canvasElement.selected:not(.reviewExtra)");const text=selected?.querySelector<HTMLElement>(".packingFitText");const font=inspectorInput(page,["Text size","Font"]);const width=inspectorInput(page,["Box width","Width"]);const height=inspectorInput(page,["Box height","Height"]);return canvas&&selected&&text&&font&&width&&height?{canvas,selected,text,font,width,height}:null;}
function mmPosition(element:HTMLElement){return{x:(Number.parseFloat(element.style.left||"0")/100)*LABEL_W,y:(Number.parseFloat(element.style.top||"0")/100)*LABEL_H};}
function measureForFont(page:HTMLElement,pt:number){const parts=selectedParts(page);if(!parts)return null;const rect=parts.canvas.getBoundingClientRect();if(!rect.width)return null;const pxPerMm=rect.width/LABEL_W;const px=pt*(96/72)*(rect.width/400);const context=document.createElement("canvas").getContext("2d");if(!context)return null;const style=getComputedStyle(parts.text);context.font=`${Number.parseInt(style.fontWeight||"400",10)>=600?700:400} ${px}px ${style.fontFamily||"Arial"}`;const raw=parts.text.dataset.finalRawText||parts.text.textContent||" ";const lines=raw.split("\n");const widest=Math.max(1,...lines.map(line=>context.measureText(line||" ").width));return{...parts,px,w:clamp(widest/pxPerMm+.35,1.2,LABEL_W),h:clamp(lines.length*px*1.04/pxPerMm+.25,1.2,LABEL_H)};}
function nudgeSelected(selected:HTMLElement,key:"ArrowLeft"|"ArrowUp",millimetres:number){const whole=Math.max(0,Math.ceil(millimetres));for(let i=0;i<whole;i+=1){selected.dispatchEvent(new KeyboardEvent("keydown",{key,shiftKey:true,bubbles:true,cancelable:true}));}}
function applyFontGrowth(page:HTMLElement){const parts=selectedParts(page);if(!parts)return;const pt=clamp(Number(parts.font.value)||8,3,120);if(String(pt)!==parts.font.value)parts.font.value=String(pt);const measured=measureForFont(page,pt);if(!measured)return;const pos=mmPosition(measured.selected);const overflowX=Math.max(0,pos.x+measured.w-LABEL_W);const overflowY=Math.max(0,pos.y+measured.h-LABEL_H);if(overflowX)nudgeSelected(measured.selected,"ArrowLeft",overflowX);if(overflowY)nudgeSelected(measured.selected,"ArrowUp",overflowY);window.setTimeout(()=>{const fresh=selectedParts(page);if(!fresh)return;const nextW=String(Math.round(measured.w*4)/4);const nextH=String(Math.round(measured.h*4)/4);if(fresh.width.value!==nextW)setReactInput(fresh.width,nextW);if(fresh.height.value!==nextH)setReactInput(fresh.height,nextH);requestAnimationFrame(()=>{const latest=selectedParts(page);if(!latest)return;let px=measured.px;latest.text.style.setProperty("font-size",`${px}px`,"important");latest.text.style.setProperty("line-height","1.02","important");let guard=0;while((latest.text.scrollWidth>latest.text.clientWidth+1||latest.text.scrollHeight>latest.text.clientHeight+1)&&px>5&&guard<240){px-=.5;latest.text.style.setProperty("font-size",`${px}px`,"important");guard+=1;}latest.text.dataset.packingScaledPx=String(px);});},0);}
function tightenSelected(page:HTMLElement){const parts=selectedParts(page);if(!parts)return;const measured=measureForFont(page,clamp(Number(parts.font.value)||8,3,120));if(!measured)return;const nextW=String(Math.round(measured.w*4)/4);const nextH=String(Math.round(measured.h*4)/4);if(parts.width.value!==nextW)setReactInput(parts.width,nextW);if(parts.height.value!==nextH)setReactInput(parts.height,nextH);requestAnimationFrame(()=>applyFontGrowth(page));}

function stabilizeMenu(){document.querySelectorAll<HTMLElement>(".moduleMenu").forEach(menu=>menu.classList.add("reviewFinalMenu"));}
function stabilizeHome(){document.querySelectorAll<HTMLElement>(".seikoOperationalDashboard").forEach(dashboard=>{const button=Array.from(dashboard.querySelectorAll<HTMLButtonElement>("button")).find(node=>node.textContent?.trim()==="Customize dashboard");if(!button)return;const host=dashboard.closest<HTMLElement>(".overview")||dashboard.parentElement||dashboard;host.classList.add("reviewFinalDashboardHost");let footer=host.querySelector<HTMLElement>(":scope > .reviewFinalDashboardFooter");if(!footer){footer=document.createElement("div");footer.className="reviewFinalDashboardFooter";host.appendChild(footer);}else if(footer!==host.lastElementChild){host.appendChild(footer);}if(button.parentElement!==footer)footer.appendChild(button);});}
function stabilizeOrders(){document.querySelectorAll<HTMLElement>(".ordersPage").forEach(page=>{const head=page.querySelector<HTMLElement>(".orderCenterHead");if(!head)return;head.classList.add("reviewFinalOrderHead");const back=head.querySelector<HTMLButtonElement>(".finalSessionBack")||page.querySelector<HTMLButtonElement>(".finalSessionBack");if(back){let row=page.querySelector<HTMLElement>(".reviewFinalBackRow");if(!row){row=document.createElement("div");row.className="reviewFinalBackRow";head.insertAdjacentElement("beforebegin",row);}if(back.parentElement!==row)row.appendChild(back);}});}

function addExtra(page:HTMLElement,kind:ExtraKind){let value="";if(kind==="text"){value=prompt("Fixed text to print on this label:","")?.trim()||"";if(!value)return;}const extra:Extra={id:crypto.randomUUID(),kind,value,x:kind==="qr"?39:3,y:kind==="barcode"?19:14,w:kind==="qr"?8:kind==="barcode"?30:15,h:kind==="qr"?8:kind==="barcode"?4:3.5,font:7};writeExtras([...readExtras(),extra]);renderExtras(page,true);}
function extraText(extra:Extra,index:number,total:number,page:HTMLElement){if(extra.kind==="sequence")return`${index+1} of ${total}`;if(extra.kind==="qr"||extra.kind==="barcode"){const order=(page.querySelector(".labelTopbar .eyebrow")?.textContent||"").replace(/^ORDER\s+/i,"").split("·")[0]?.trim()||"ORDER";return`${order}:${index+1}`;}return extra.value;}
function renderExtra(node:HTMLElement,extra:Extra,text:string){node.replaceChildren();if(extra.kind==="qr"){const span=document.createElement("span");span.className="reviewQr";span.textContent="▦";node.appendChild(span);}else if(extra.kind==="barcode"){const span=document.createElement("span");span.className="reviewBarcode";const bars=document.createElement("i");const small=document.createElement("small");small.textContent=text;span.append(bars,small);node.appendChild(span);}else node.textContent=text;}
function renderExtras(page:HTMLElement,force=false){const extras=readExtras();const canvas=page.querySelector<HTMLElement>(".packingCanvas");const sample=page.querySelector<HTMLSelectElement>(".labelPreviewSample select");const previewIndex=Math.max(0,sample?.selectedIndex||0);const previewTotal=sample?.options.length||page.querySelectorAll(".labelSidebar .record").length||1;const labels=[...page.querySelectorAll<HTMLElement>(".printSheet .printedLabel")];const signature=`${JSON.stringify(extras)}|${sample?.value||previewIndex}|${previewTotal}|${labels.length}`;if(canvas&&!force&&canvas.dataset.reviewExtraSignature===signature)return;if(canvas){canvas.dataset.reviewExtraSignature=signature;canvas.querySelectorAll(".reviewExtra").forEach(n=>n.remove());extras.forEach(extra=>{const node=document.createElement("div");node.className=`canvasElement reviewExtra reviewExtra-${extra.kind}`;node.style.left=`${extra.x/LABEL_W*100}%`;node.style.top=`${extra.y/LABEL_H*100}%`;node.style.width=`${extra.w/LABEL_W*100}%`;node.style.height=`${extra.h/LABEL_H*100}%`;node.style.fontSize=`${extra.font*(96/72)*(canvas.getBoundingClientRect().width/400)}px`;renderExtra(node,extra,extraText(extra,previewIndex,previewTotal,page));canvas.appendChild(node);});}labels.forEach((label,index)=>{label.querySelectorAll(".reviewPrintExtra").forEach(n=>n.remove());extras.forEach(extra=>{const node=document.createElement("div");node.className="printedElement reviewPrintExtra";node.style.left=`${extra.x}mm`;node.style.top=`${extra.y}mm`;node.style.width=`${extra.w}mm`;node.style.height=`${extra.h}mm`;node.style.fontSize=`${extra.font}pt`;renderExtra(node,extra,extraText(extra,index,labels.length,page));label.appendChild(node);});});}
function clickInfo(page:HTMLElement,label:string){const choice=Array.from(page.querySelectorAll<HTMLElement>(".packingInfoGrid .fieldChoice")).find(node=>node.querySelector("label span")?.textContent?.trim()===label);const input=choice?.querySelector<HTMLInputElement>('input[type="checkbox"]');if(input&&!input.checked)input.click();}
function stabilizeTrace(page:HTMLElement){if(page.querySelector(".reviewTraceTools"))return;const host=page.querySelector<HTMLElement>(".labelSidebar");if(!host)return;page.querySelectorAll(".finalTraceTools").forEach(node=>node.classList.add("reviewOldTraceHidden"));const tools=document.createElement("section");tools.className="reviewTraceTools";tools.innerHTML='<p class="eyebrow">TRACE & CODES</p><p>Use trace/code elements without leaving this label set.</p><div><button type="button" data-tool="number">Label number</button><button type="button" data-tool="order">Order number</button><button type="button" data-tool="sequence">Sequence</button><button type="button" data-tool="text">Fixed text</button><button type="button" data-tool="qr">QR code</button><button type="button" data-tool="barcode">Barcode</button></div>';
tools.querySelectorAll<HTMLButtonElement>("[data-tool]").forEach(button=>button.addEventListener("click",()=>{const tool=button.dataset.tool||"";if(tool==="number")clickInfo(page,"Label number / total");else if(tool==="order")clickInfo(page,"Order number");else addExtra(page,tool as ExtraKind);}));host.appendChild(tools);}
function stabilizePacking(page:HTMLElement){page.classList.add("reviewFinalPacking");const font=inspectorInput(page,["Text size","Font"]);if(font){font.min="3";font.max="120";font.step=".5";}const fit=page.querySelector<HTMLButtonElement>(".packingFitBoxButton");if(fit&&!fit.dataset.reviewFinal){fit.dataset.reviewFinal="true";fit.textContent="Tight fit";fit.addEventListener("click",event=>{event.preventDefault();event.stopImmediatePropagation();tightenSelected(page);},true);}const selected=selectedParts(page);if(selected&&!selected.text.dataset.reviewInitialFont){selected.text.dataset.reviewInitialFont="true";window.setTimeout(()=>applyFontGrowth(page),0);}stabilizeTrace(page);renderExtras(page);}

export function SeikoReviewFinal(){useEffect(()=>{const controller=startDomEnhancement(()=>{stabilizeMenu();stabilizeHome();stabilizeOrders();document.querySelectorAll<HTMLElement>(".packingWorkflowDesigner").forEach(stabilizePacking);},{observer:{childList:true,subtree:true,attributes:true,attributeFilter:["class","style","open"]}});const input=(event:Event)=>{const target=event.target as HTMLInputElement|null;const page=target?.closest<HTMLElement>(".packingWorkflowDesigner");if(!target||!page)return;const font=inspectorInput(page,["Text size","Font"]);if(target===font)window.setTimeout(()=>applyFontGrowth(page),0);};const change=()=>controller.schedule();document.addEventListener("input",input,true);document.addEventListener("change",change,true);window.addEventListener("resize",controller.schedule);return()=>{document.removeEventListener("input",input,true);document.removeEventListener("change",change,true);window.removeEventListener("resize",controller.schedule);controller.stop();};},[]);return null;}
