"use client";

import { useCallback, useEffect, useState } from "react";
import type { ClientLibraryRecord } from "./lib/business-library";
import { newSeikoClient, normalizeClientType, requestSeikoClients, SEIKO_CLIENT_TYPES, type SeikoClientRecord } from "./lib/seiko-clients";

export function SeikoClientDirectory({ legacyRecords = [] }: { legacyRecords?: ClientLibraryRecord[] }) {
  const [clients, setClients] = useState<SeikoClientRecord[]>([]); const [query, setQuery] = useState(""); const [archived, setArchived] = useState(false);
  const [editing, setEditing] = useState<SeikoClientRecord | null>(null); const [canManage, setCanManage] = useState(false); const [busy, setBusy] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setBusy(true); setError(""); try { const result = await requestSeikoClients({ operation: "list" }); setClients(result.clients); setCanManage(result.canManage); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = clients.filter(client => client.archived === archived && `${client.name} ${client.type} ${client.contactPerson} ${client.phone} ${client.email}`.toLowerCase().includes(query.toLowerCase()));
  async function save(client: SeikoClientRecord) { setBusy(true); setError(""); try { const result = await requestSeikoClients({ operation: "save", client }); setClients(result.clients); setEditing(null); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  async function importLegacy() { setBusy(true); setError(""); try { const records = legacyRecords.filter(item => item.name.trim() && item.phone.trim()).map(item => ({ ...item, type: normalizeClientType(item.type) })); const result = await requestSeikoClients({ operation: "import", clients: records }); setClients(result.clients); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } }
  return <div className="phase2Workspace"><div className="phase2Toolbar"><input aria-label="Find client" value={query} onChange={event => setQuery(event.target.value)} placeholder="Name, phone, email or contact person"/><label className="phase2Check"><input type="checkbox" checked={archived} onChange={event => setArchived(event.target.checked)}/>Archived</label>{legacyRecords.some(item => item.name.trim() && item.phone.trim()) && <button className="secondary" disabled={!canManage || busy} onClick={() => void importLegacy()}>Import saved browser clients</button>}<button className="primary" disabled={!canManage || busy} onClick={() => setEditing(newSeikoClient())}>+ Add client</button></div>{error && <p className="billingError" role="alert">{error}</p>}<p role="status">{busy ? "Loading clients…" : `${visible.length} ${archived ? "archived" : "active"} clients`}</p><section className="phase2LibraryList">{visible.map(client => <article className="phase2LibraryRow" key={client.id}><div><b>{client.name}</b><small>{SEIKO_CLIENT_TYPES.find(item => item.value === client.type)?.label} · {[client.contactPerson,client.phone,client.email].filter(Boolean).join(" · ")}</small></div><div><button className="secondary" disabled={!canManage} onClick={() => setEditing({ ...client })}>Edit</button><button className="secondary" disabled={!canManage || busy} onClick={() => void save({ ...client, archived: !client.archived })}>{client.archived ? "Restore" : "Archive"}</button></div></article>)}{!busy && !visible.length && <div className="phase2Empty">No clients match this view.</div>}</section>{editing && <ClientEditor client={editing} busy={busy} error={error} onCancel={() => setEditing(null)} onSave={save}/>}</div>;
}

export function ClientEditor({ client, busy, error, compact = false, onCancel, onSave }: { client: SeikoClientRecord; busy: boolean; error?: string; compact?: boolean; onCancel: () => void; onSave: (client: SeikoClientRecord) => void | Promise<void> }) {
  const [draft, setDraft] = useState(client); const [problem, setProblem] = useState("");
  const submit = () => { if (!draft.name.trim() || !draft.phone.trim()) { setProblem("Client name and phone are required."); return; } void onSave(draft); };
  const fields = <><label>Client type<select value={draft.type} onChange={event => setDraft({ ...draft, type: event.target.value as SeikoClientRecord["type"] })}>{SEIKO_CLIENT_TYPES.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><Field label="Client / organisation name *" value={draft.name} onChange={name => setDraft({ ...draft, name })}/><Field label="Contact person" value={draft.contactPerson} onChange={contactPerson => setDraft({ ...draft, contactPerson })}/><Field label="Phone *" value={draft.phone} onChange={phone => setDraft({ ...draft, phone })}/><Field label="Email" value={draft.email} onChange={email => setDraft({ ...draft, email })}/><Field label="GSTIN" value={draft.gstin} onChange={gstin => setDraft({ ...draft, gstin })}/><Field label="Billing address" value={draft.billingAddress} onChange={billingAddress => setDraft({ ...draft, billingAddress })}/><Field label="Delivery address" value={draft.deliveryAddress} onChange={deliveryAddress => setDraft({ ...draft, deliveryAddress })}/>{(problem || error) && <p className="billingError billingFull" role="alert">{problem || error}</p>}</>;
  if (compact) return <section className="billingInlineClient"><h3>Create client without leaving this invoice</h3><div className="billingFields">{fields}</div><div className="phase2Actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button type="button" className="primary" disabled={busy} onClick={submit}>{busy ? "Saving…" : "Save client"}</button></div></section>;
  return <div className="phase2Scrim"><form className="phase2Editor" role="dialog" aria-modal="true" aria-label="Client" onSubmit={event => { event.preventDefault(); submit(); }}><header><h2>{client.name ? "Edit client" : "Add client"}</h2><button type="button" aria-label="Close" onClick={onCancel}>×</button></header><fieldset className="phase2EditorBody" disabled={busy}>{fields}</fieldset><footer><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button type="submit" className="primary" disabled={busy}>{busy ? "Saving…" : "Save client"}</button></footer></form></div>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label>{label}<input value={value} onChange={event => onChange(event.target.value)}/></label>; }
