import "../../app/globals.css";
import "../../app/logo-fixes.css";
import "../../app/label-designer.css";
import "../../app/label-designer-polish.css";
import "../../app/label-production-ready.css";
import "../../app/label-finalization.css";
import "../../app/label-no-order.css";
import "../../app/label-records.css";
import "../../app/production.css";
import "../../app/integrated-theme.css";
import "../../app/orders.css";
import "../../app/order-enhancements.css";
import "../../app/workspace-grid.css";
import "../../app/app-ui-system.css";
import "../../app/ui-regression-fixes.css";
import "../../app/order-setup-polish.css";
import "../../app/order-compact-ux.css";
import "../../app/brand-header-final.css";
import "../../app/label-flow-polish.css";
import "../../app/label-controls.css";
import "../../app/label-print-safety.css";
import "../../app/global-navigation.css";
import "../../app/control-consistency.css";
import "../../app/access-control.css";
import "../../app/modern-auth.css";
import "../../app/jinam-shell.css";
import "../../app/channel-connections.css";
import "../../app/meth-commerce-settings.css";
import "../../app/seiko-meth.css";
import "../../app/veyn-app.css";
import "../../app/veyn-functional.css";
import "../../app/phase1-visual.css";
import "../../app/seiko-phase1.css";
import "../../app/seiko-phase2.css";
import "../../app/seiko-stage2-safe.css";
import "../../app/seiko-workspace-label-final.css";
import "../../app/seiko-list-center-enhancements.css";
import "../../app/seiko-refinement.css";
import "../../app/seiko-operational-ux.css";
import "../../app/seiko-interface-fixes.css";
import "../../app/packing-workspace-audit.css";
import "../../app/packing-workflow-final.css";
import "../../app/seiko-stable.css";
import { createRoot } from "react-dom/client";
import { AccessProvider } from "../../app/access-control";
import { BusinessApplicationRouter } from "../../app/business-application-router";
import Home from "../../app/page";
createRoot(document.getElementById("root")!).render(<AccessProvider><BusinessApplicationRouter><Home/></BusinessApplicationRouter></AccessProvider>);
